accent = "#50c878"
cursor = "#f0f0f5"
foreground = "#f0f0f5"
background = "#0d1213"
selection_foreground = "#0d1213"
selection_background = "#3a7f96"

color0 = "#20272a"
color1 = "#ff6464"
color2 = "#34e094"
color3 = "#fbbf24"
color4 = "#50c878"
color5 = "#c084fc"
color6 = "#60dbdb"
color7 = "#b9bbc3"
color8 = "#3c474c"
color9 = "#ff8585"
color10 = "#67f0b2"
color11 = "#ffd166"
color12 = "#7dd3fc"
color13 = "#d8b4fe"
color14 = "#8be9e9"
color15 = "#f0f0f5"
