// Generated by `mise run mobile-models-generate`. DO NOT EDIT.
package dev.verdeai.core

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement

// Encode Event/Effect through their sealed base type to include the discriminator.
val CoreJson = Json { ignoreUnknownKeys = true; encodeDefaults = true; explicitNulls = true }

@Serializable
data class TerminalConfig(
    val `api_version`: Long = 1,
    val `cols`: Int,
    val `rows`: Int,
    val `scrollback_rows`: Long,
)

@Serializable
enum class TerminalCursorShape {
    `block`,
    `underline`,
    `bar`,
}

@Serializable
data class TerminalCursor(
    val `row`: Int,
    val `col`: Int,
    val `visible`: Boolean,
    val `shape`: TerminalCursorShape,
)

@Serializable
data class TerminalCell(
    val `text`: String,
    val `width`: Int,
    val `fg`: String,
    val `bg`: String,
    val `bold`: Boolean,
    val `italic`: Boolean,
    val `underline`: Boolean,
    val `strikethrough`: Boolean,
    val `inverse`: Boolean,
)

@Serializable
data class TerminalSnapshot(
    val `api_version`: Long = 1,
    val `revision`: String,
    val `cols`: Int,
    val `rows`: Int,
    val `scroll_offset`: Long,
    val `scrollback_rows`: Long,
    val `reply_bytes_base64`: String,
    val `reverse_video`: Boolean,
    val `vt_modes`: VtModes,
    val `cursor`: TerminalCursor,
    val `cells`: List<TerminalCell>,
    val `title`: String,
)

@Serializable
data class TerminalView(
    val `terminal_id`: String,
    val `workspace_id`: String = "",
    val `label`: String = "Terminal",
    val `session_status`: String = "running",
    val `attached`: Boolean = false,
    val `cols`: Int = 80,
    val `rows`: Int = 24,
    val `next_offset`: String? = null,
    val `grid_revision`: String = "0",
    val `stale`: Boolean = true,
    val `error`: LocalError? = null,
)

@Serializable
data class TerminalQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: TerminalView?,
    val `error`: LocalError?,
)

@Serializable
data class ChatAttachment(
    val `local_id`: String,
    val `name`: String,
    val `mime`: String,
    val `byte_size`: String,
    val `attachment_id`: String? = null,
    val `reference`: String? = null,
    val `uploaded_bytes`: String = "0",
    val `status`: String = "local",
    val `error`: LocalError? = null,
)

@Serializable
data class ChatTool(
    val `id`: String,
    val `kind`: String,
    val `status`: String,
)

@Serializable
data class ChatRow(
    val `id`: String,
    val `role`: String,
    val `kind`: String = "message",
    val `author`: String = "",
    val `body`: String,
    val `created_at_ms`: Long? = null,
    val `delivery`: String = "committed",
    val `attachments`: List<ChatAttachment> = emptyList(),
    val `tool`: ChatTool? = null,
)

@Serializable
data class ChatTurn(
    val `turn_id`: String,
    val `status`: String,
    val `after_seq`: String = "0",
    val `started_at_ms`: Long? = null,
    val `elapsed_ms`: Long = 0,
    val `stop_pending`: Boolean = false,
)

@Serializable
data class ChatApproval(
    val `turn_id`: String,
    val `call_id`: String,
    val `title`: String,
    val `body`: String,
    val `resolution`: String = "idle",
    val `error`: LocalError? = null,
)

@Serializable
data class ChatFollowup(
    val `id`: String,
    val `kind`: String,
    val `state`: String = "pending",
    val `delivery`: String = "unsent",
    val `turn_id`: String,
    val `steer_id`: String,
    val `next_turn_id`: String,
    val `text`: String,
    val `attachments`: List<ChatAttachment> = emptyList(),
    val `paused`: Boolean = false,
    val `can_retry`: Boolean = false,
    val `can_pull_back`: Boolean = true,
    val `error`: LocalError? = null,
)

@Serializable
data class ChatSelection(
    val `provider`: String? = null,
    val `model`: String? = null,
    val `effort`: String? = null,
    val `access`: String? = null,
    val `speed`: String? = null,
)

@Serializable
data class ChatChoice(
    val `id`: String,
    val `label`: String,
    val `enabled`: Boolean = true,
    val `reason`: String? = null,
    val `favorite`: Boolean = false,
)

@Serializable
data class ChatCatalogs(
    val `models`: List<ChatChoice> = emptyList(),
    val `efforts`: List<ChatChoice> = emptyList(),
    val `access`: List<ChatChoice> = emptyList(),
    val `speeds`: List<ChatChoice> = emptyList(),
    val `slash`: List<ChatChoice> = emptyList(),
)

@Serializable
data class ChatDraft(
    val `revision`: String,
    val `text`: String,
    val `attachments`: List<ChatAttachment>,
    val `persisted`: Boolean,
)

@Serializable
data class ChatMention(
    val `path`: String,
    val `label`: String,
)

@Serializable
data class ChatShellConfirmation(
    val `id`: String,
    val `command`: String,
    val `cwd`: String,
)

@Serializable
data class ChatUsageLimit(
    val `label`: String,
    val `percent_left`: Int,
    val `reset`: String,
)

@Serializable
data class ChatUsageStat(
    val `label`: String,
    val `value`: String,
)

@Serializable
data class ChatUsage(
    val `provider`: String,
    val `limits`: List<ChatUsageLimit> = emptyList(),
    val `stats`: List<ChatUsageStat> = emptyList(),
    val `recent`: List<ChatUsageStat> = emptyList(),
)

@Serializable
data class ChatPage(
    val `has_older`: Boolean,
    val `cursor`: String?,
    val `loading`: Boolean,
)

@Serializable
data class ChatThreadView(
    val `thread`: ThreadSummary,
    val `rows`: List<ChatRow>,
    val `page`: ChatPage,
    val `turn`: ChatTurn?,
    val `approval`: ChatApproval?,
    val `usage`: ChatUsage?,
    val `stale`: Boolean,
    val `error`: LocalError?,
)

@Serializable
data class ChatComposerView(
    val `draft`: ChatDraft,
    val `selection`: ChatSelection,
    val `catalogs`: ChatCatalogs,
    val `mentions`: List<ChatMention>,
    val `provider_ready`: Boolean,
    val `can_send`: Boolean,
    val `can_stop`: Boolean,
    val `send_operation`: Operation?,
    val `followup`: ChatFollowup?,
    val `shell_confirmation`: ChatShellConfirmation?,
    val `error`: LocalError?,
)

@Serializable
data class ThreadQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: ChatThreadView?,
    val `error`: LocalError?,
)

@Serializable
data class ComposerQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: ChatComposerView?,
    val `error`: LocalError?,
)

@Serializable
data class Config(
    val `api_version`: Long,
    val `host_id`: String,
    val `label`: String,
    val `https_url`: String?,
    val `wss_url`: String?,
    val `client_revision`: Long,
    val `session_nonce`: String,
    val `jitter_seed`: ULong,
)

@Serializable
enum class Lifecycle {
    `created`,
    `foreground`,
    `background`,
    `stopped`,
}

@Serializable
data class LocalError(
    val `domain`: String = "input",
    val `code`: String,
    val `message`: String,
    val `failure_kind`: String? = null,
    val `retryable`: Boolean = false,
    val `retry_after_ms`: Long? = null,
    val `intent_id`: String? = null,
    val `rpc_code`: String? = null,
    val `delivery`: String? = "rejected",
)

@Serializable
data class Operation(
    val `intent_id`: String,
    val `state`: String = "failed",
    val `error`: LocalError?,
)

@Serializable
enum class TransportFailureKind {
    `network`,
    `timeout`,
    `cancelled`,
    `tls`,
    `server_unavailable`,
    `resource`,
}

@Serializable
enum class TransportFailureCode {
    `unknown`,
    `offline`,
    `dns`,
    `refused`,
    `reset`,
    `timeout`,
    `cancelled`,
    `certificate`,
    `hostname`,
    `pin_mismatch`,
    `unavailable`,
    `resource`,
}

@Serializable
data class TransportFailure(
    val `kind`: TransportFailureKind,
    val `code`: TransportFailureCode,
)

@Serializable
enum class PlatformFailureCode {
    `unavailable`,
    `locked`,
    `denied`,
    `io`,
    `resource`,
}

@Serializable
data class PlatformFailure(
    val `code`: PlatformFailureCode,
)

@Serializable
data class Header(
    val `name`: String,
    val `value`: String,
)

@Serializable
data class Tls(
    val `origin`: String,
    val `spki_sha256`: String,
)

@Serializable
data class VtModes(
    val `application_cursor`: Boolean,
    val `bracketed_paste`: Boolean,
)

@Serializable
data class AttachmentInput(
    val `local_id`: String,
    val `name`: String,
    val `mime`: String,
    val `byte_size`: String,
    val `bytes_base64`: String,
)

@Serializable
sealed class Event

@Serializable
@SerialName("sign_out")
data class EventSignOut(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `host_id`: String,
) : Event()

@Serializable
@SerialName("forget_host")
data class EventForgetHost(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `host_id`: String,
) : Event()

@Serializable
@SerialName("start")
data class EventStart(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `foreground`: Boolean,
    val `network_available`: Boolean,
) : Event()

@Serializable
@SerialName("foreground")
data class EventForeground(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
) : Event()

@Serializable
@SerialName("background")
data class EventBackground(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
) : Event()

@Serializable
@SerialName("shutdown")
data class EventShutdown(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
) : Event()

@Serializable
@SerialName("network_changed")
data class EventNetworkChanged(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `available`: Boolean,
    val `network_id`: String,
) : Event()

@Serializable
@SerialName("http_response")
data class EventHttpResponse(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `status`: Int?,
    val `headers`: List<Header>,
    val `body_base64`: String?,
    val `error`: TransportFailure?,
) : Event()

@Serializable
@SerialName("ws_open")
data class EventWsOpen(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `socket_id`: String,
    val `generation`: String,
    val `protocol`: String,
) : Event()

@Serializable
@SerialName("ws_message")
data class EventWsMessage(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `socket_id`: String,
    val `generation`: String,
    val `text`: String,
) : Event()

@Serializable
@SerialName("ws_closed")
data class EventWsClosed(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `socket_id`: String,
    val `generation`: String,
    val `code`: Int?,
    val `clean`: Boolean,
    val `error`: TransportFailure?,
) : Event()

@Serializable
@SerialName("timer_fired")
data class EventTimerFired(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `timer_id`: String,
    val `generation`: String,
) : Event()

@Serializable
@SerialName("secure_store_value")
data class EventSecureStoreValue(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
    val `value_base64`: String?,
    val `error`: PlatformFailure?,
) : Event()

@Serializable
@SerialName("secure_store_done")
data class EventSecureStoreDone(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
    val `error`: PlatformFailure?,
) : Event()

@Serializable
@SerialName("tls_peer")
data class EventTlsPeer(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `origin`: String,
    val `spki_sha256`: String,
    val `system_trusted`: Boolean,
) : Event()

@Serializable
@SerialName("terminal_applied")
data class EventTerminalApplied(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `terminal_id`: String,
    val `grid_revision`: String,
    val `error`: PlatformFailure?,
) : Event()

@Serializable
@SerialName("terminal_reply")
data class EventTerminalReply(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `terminal_id`: String,
    val `bytes_base64`: String,
) : Event()

@Serializable
@SerialName("pair")
data class EventPair(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `link`: String,
    val `device_label`: String,
    val `client_nonce`: String,
) : Event()

@Serializable
@SerialName("trust_decision")
data class EventTrustDecision(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `proposal_id`: String,
    val `accept`: Boolean,
) : Event()

@Serializable
@SerialName("retry_connection")
data class EventRetryConnection(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
) : Event()

@Serializable
@SerialName("focus")
data class EventFocus(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String?,
    val `thread_id`: String?,
    val `terminal_id`: String?,
) : Event()

@Serializable
@SerialName("history_search")
data class EventHistorySearch(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `query`: String,
    val `workspace_id`: String?,
) : Event()

@Serializable
@SerialName("history_load_more")
data class EventHistoryLoadMore(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
) : Event()

@Serializable
@SerialName("shell_confirm")
data class EventShellConfirm(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `confirmation_id`: String,
    val `accept`: Boolean,
) : Event()

@Serializable
@SerialName("terminal_create")
data class EventTerminalCreate(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `cwd`: String?,
    val `cols`: Int,
    val `rows`: Int,
) : Event()

@Serializable
@SerialName("thread_open")
data class EventThreadOpen(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
) : Event()

@Serializable
@SerialName("thread_load_older")
data class EventThreadLoadOlder(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
) : Event()

@Serializable
@SerialName("draft_set")
data class EventDraftSet(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `text`: String,
    val `attachments`: List<AttachmentInput>,
) : Event()

@Serializable
@SerialName("composer_select")
data class EventComposerSelect(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `provider`: String?,
    val `model`: String?,
    val `effort`: String?,
    val `access`: String?,
    val `speed`: String?,
) : Event()

@Serializable
@SerialName("send")
data class EventSend(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `draft_revision`: String,
) : Event()

@Serializable
@SerialName("turn_cancel")
data class EventTurnCancel(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `turn_id`: String,
) : Event()

@Serializable
enum class EventFollowupSubmitKind {
    `queue`,
    `steer`,
}

@Serializable
@SerialName("followup_submit")
data class EventFollowupSubmit(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `draft_revision`: String,
    val `kind`: EventFollowupSubmitKind,
) : Event()

@Serializable
@SerialName("followup_retry")
data class EventFollowupRetry(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `followup_id`: String,
) : Event()

@Serializable
@SerialName("followup_pull_back")
data class EventFollowupPullBack(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `followup_id`: String,
) : Event()

@Serializable
@SerialName("followup_cancel")
data class EventFollowupCancel(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `followup_id`: String,
) : Event()

@Serializable
enum class EventApprovalDecideDecision {
    `approve`,
    `deny`,
}

@Serializable
@SerialName("approval_decide")
data class EventApprovalDecide(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `turn_id`: String,
    val `call_id`: String,
    val `decision`: EventApprovalDecideDecision,
) : Event()

@Serializable
@SerialName("shell_prepare")
data class EventShellPrepare(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `command`: String,
) : Event()

@Serializable
@SerialName("slash_search")
data class EventSlashSearch(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `query`: String,
) : Event()

@Serializable
@SerialName("slash_run")
data class EventSlashRun(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `command`: String,
    val `args`: String,
) : Event()

@Serializable
@SerialName("mention_search")
data class EventMentionSearch(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `query`: String,
) : Event()

@Serializable
@SerialName("terminal_attach")
data class EventTerminalAttach(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
) : Event()

@Serializable
@SerialName("terminal_detach")
data class EventTerminalDetach(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
) : Event()

@Serializable
@SerialName("terminal_kill")
data class EventTerminalKill(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
) : Event()

@Serializable
@SerialName("terminal_resize")
data class EventTerminalResize(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
    val `cols`: Int,
    val `rows`: Int,
) : Event()

@Serializable
@SerialName("push_register")
data class EventPushRegister(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `platform`: String,
    val `send_token`: String,
    val `key_seed_base64`: String,
) : Event()

@Serializable
@SerialName("thread_rename")
data class EventThreadRename(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `title`: String,
) : Event()

@Serializable
@SerialName("thread_close")
data class EventThreadClose(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
) : Event()

@Serializable
@SerialName("thread_sync")
data class EventThreadSync(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
) : Event()

@Serializable
@SerialName("thread_create")
data class EventThreadCreate(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `provider`: String,
    val `model`: String? = null,
    val `effort`: String? = null,
    val `access`: String? = null,
    val `speed`: String? = null,
) : Event()

@Serializable
@SerialName("new_chat_select")
data class EventNewChatSelect(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `provider`: String? = null,
    val `model`: String? = null,
    val `effort`: String? = null,
    val `access`: String? = null,
    val `speed`: String? = null,
) : Event()

@Serializable
@SerialName("workspace_create")
data class EventWorkspaceCreate(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `path`: String,
    val `label`: String? = null,
) : Event()

@Serializable
@SerialName("workspace_rename")
data class EventWorkspaceRename(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `label`: String,
) : Event()

@Serializable
@SerialName("workspace_archive")
data class EventWorkspaceArchive(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `archived`: Boolean,
) : Event()

@Serializable
@SerialName("workspace_close")
data class EventWorkspaceClose(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
) : Event()

@Serializable
@SerialName("directory_list")
data class EventDirectoryList(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `path`: String? = null,
) : Event()

@Serializable
@SerialName("file_open")
data class EventFileOpen(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `path`: String,
    val `kind`: FileKind,
    val `max_bytes`: Long,
) : Event()

@Serializable
@SerialName("push_received")
data class EventPushReceived(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `turn_id`: String,
    val `kind`: String,
) : Event()

@Serializable
enum class EventTerminalInputInputKind {
    `text`,
    `key`,
    `paste`,
}

@Serializable
data class EventTerminalInputInput(
    val `kind`: EventTerminalInputInputKind,
    val `text`: String? = null,
    val `key`: String? = null,
    val `ctrl`: Boolean,
    val `alt`: Boolean,
    val `shift`: Boolean,
)

@Serializable
@SerialName("terminal_input")
data class EventTerminalInput(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
    val `vt_modes`: VtModes,
    val `input`: EventTerminalInputInput,
) : Event()

@Serializable
sealed class Effect

@Serializable
@SerialName("http_request")
data class EffectHttpRequest(
    val `effect_id`: String,
    val `generation`: String,
    val `method`: String,
    val `url`: String,
    val `headers`: List<Header>,
    val `body_base64`: String?,
    val `timeout_ms`: Long,
    val `max_response_bytes`: Long,
    val `tls`: Tls,
) : Effect()

@Serializable
@SerialName("http_cancel")
data class EffectHttpCancel(
    val `effect_id`: String,
    val `generation`: String,
    val `request_id`: String,
) : Effect()

@Serializable
@SerialName("ws_open")
data class EffectWsOpen(
    val `effect_id`: String,
    val `generation`: String,
    val `url`: String,
    val `protocols`: List<String>,
    val `tls`: Tls,
    val `max_message_bytes`: Long,
) : Effect()

@Serializable
@SerialName("ws_send")
data class EffectWsSend(
    val `effect_id`: String,
    val `generation`: String,
    val `socket_id`: String,
    val `text`: String,
) : Effect()

@Serializable
@SerialName("ws_close")
data class EffectWsClose(
    val `effect_id`: String,
    val `generation`: String,
    val `socket_id`: String,
    val `code`: Int,
) : Effect()

@Serializable
@SerialName("set_timer")
data class EffectSetTimer(
    val `effect_id`: String,
    val `generation`: String,
    val `timer_id`: String,
    val `delay_ms`: Long,
    val `purpose`: String,
) : Effect()

@Serializable
@SerialName("cancel_timer")
data class EffectCancelTimer(
    val `effect_id`: String,
    val `generation`: String,
    val `timer_id`: String,
) : Effect()

@Serializable
@SerialName("secure_store_get")
data class EffectSecureStoreGet(
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
) : Effect()

@Serializable
@SerialName("secure_store_put")
data class EffectSecureStorePut(
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
    val `value_base64`: String,
) : Effect()

@Serializable
@SerialName("secure_store_delete")
data class EffectSecureStoreDelete(
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
) : Effect()

@Serializable
@SerialName("state_changed")
data class EffectStateChanged(
    val `effect_id`: String,
    val `generation`: String,
    val `revision`: String,
    val `scopes`: List<String>,
) : Effect()

@Serializable
data class EffectNotifyTarget(
    val `host_id`: String,
    val `workspace_id`: String?,
    val `thread_id`: String?,
)

@Serializable
@SerialName("notify")
data class EffectNotify(
    val `effect_id`: String,
    val `generation`: String,
    val `notification_id`: String,
    val `kind`: String,
    val `title`: String,
    val `body`: String,
    val `target`: EffectNotifyTarget,
    val `actions`: List<String>,
) : Effect()

@Serializable
@SerialName("log")
data class EffectLog(
    val `effect_id`: String,
    val `generation`: String,
    val `level`: String,
    val `code`: String,
    val `fields`: JsonElement,
) : Effect()

@Serializable
@SerialName("tls_probe")
data class EffectTlsProbe(
    val `effect_id`: String,
    val `generation`: String,
    val `origin`: String,
) : Effect()

@Serializable
@SerialName("terminal_output")
data class EffectTerminalOutput(
    val `effect_id`: String,
    val `generation`: String,
    val `terminal_id`: String,
    val `reset`: Boolean,
    val `bytes_base64`: String,
    val `next_offset`: String,
) : Effect()

@Serializable
@SerialName("file_fetch")
data class EffectFileFetch(
    val `effect_id`: String,
    val `generation`: String,
    val `intent_id`: String,
    val `url`: String,
    val `headers`: List<Header>,
    val `timeout_ms`: Long,
    val `max_response_bytes`: Long,
    val `tls`: Tls,
) : Effect()

@Serializable
data class EffectBatch(
    val `api_version`: Long,
    val `revision`: String,
    val `effects`: List<Effect>,
)

@Serializable
data class TrustProposal(
    val `id`: String,
    val `origin`: String,
    val `spki_sha256`: String,
    val `runtime_id`: String?,
)

@Serializable
data class HostView(
    val `host_id`: String,
    val `label`: String,
    val `https_url`: String?,
    val `runtime_id`: String?,
    val `instance_id`: String?,
    val `phase`: String,
    val `lifecycle`: Lifecycle,
    val `auth_state`: String,
    val `sync_state`: String,
    val `capabilities`: List<String>,
    val `scopes`: List<String>,
    val `retry_at_ms`: Long?,
    val `trust_proposal`: TrustProposal?,
    val `update_required`: Boolean,
    val `error`: LocalError?,
)

@Serializable
data class HostsView(
    val `items`: List<HostView>,
    val `operations`: List<Operation>,
)

@Serializable
data class OperationsView(
    val `items`: List<Operation>,
)

@Serializable
data class HomeView(
    val `items`: List<Pane>,
    val `loading`: Boolean,
    val `stale`: Boolean,
    val `incomplete_scopes`: List<String>,
    val `error`: LocalError?,
)

@Serializable
data class HistoryView(
    val `query`: String,
    val `items`: List<ThreadSummary>,
    val `next_cursor`: String?,
    val `loading`: Boolean,
    val `error`: LocalError?,
)

@Serializable
data class WorkspacesView(
    val `items`: List<Workspace>,
    val `loading`: Boolean,
    val `stale`: Boolean,
    val `error`: LocalError?,
    val `history`: HistoryView,
)

@Serializable
data class HostsQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: HostsView?,
    val `error`: LocalError?,
)

@Serializable
data class OperationsQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: OperationsView?,
    val `error`: LocalError?,
)

@Serializable
data class HomeQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: HomeView?,
    val `error`: LocalError?,
)

@Serializable
data class WorkspacesQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: WorkspacesView?,
    val `error`: LocalError?,
)

@Serializable
data class RenderSpan(
    val `start`: ULong,
    val `end`: ULong,
    val `kind`: String,
)

@Serializable
data class FileCitation(
    val `path`: String,
    val `line`: ULong? = null,
    val `end_line`: ULong? = null,
)

@Serializable
data class MarkdownNode(
    val `kind`: String,
    val `start`: ULong,
    val `end`: ULong,
    val `text`: String? = null,
    val `level`: Int? = null,
    val `ordered`: Boolean? = null,
    val `url`: String? = null,
    val `language`: String? = null,
    val `children`: List<MarkdownNode> = emptyList(),
    val `citation`: FileCitation? = null,
)

@Serializable
data class MarkdownView(
    val `nodes`: List<MarkdownNode>,
)

@Serializable
data class HighlightView(
    val `spans`: List<RenderSpan>,
)

@Serializable
data class DiffLine(
    val `kind`: String,
    val `text`: String,
    val `old_line`: ULong? = null,
    val `new_line`: ULong? = null,
    val `spans`: List<RenderSpan> = emptyList(),
)

@Serializable
data class DiffHunk(
    val `old_start`: ULong,
    val `old_count`: ULong,
    val `new_start`: ULong,
    val `new_count`: ULong,
    val `lines`: List<DiffLine>,
)

@Serializable
data class DiffFile(
    val `old_path`: String?,
    val `new_path`: String?,
    val `binary`: Boolean,
    val `hunks`: List<DiffHunk>,
)

@Serializable
data class DiffView(
    val `files`: List<DiffFile>,
)

@Serializable
data class MarkdownQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: MarkdownView?,
    val `error`: LocalError?,
)

@Serializable
data class HighlightQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: HighlightView?,
    val `error`: LocalError?,
)

@Serializable
data class DiffQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: DiffView?,
    val `error`: LocalError?,
)

@Serializable
data class DiffIndexEntry(
    val `path`: String,
    val `additions`: ULong,
    val `deletions`: ULong,
    val `start`: ULong,
    val `end`: ULong,
    val `patch_start`: ULong,
)

@Serializable
data class DiffIndexView(
    val `files`: List<DiffIndexEntry>,
)

@Serializable
data class DiffIndexQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: DiffIndexView?,
    val `error`: LocalError?,
)

@Serializable
data class Pane(
    val `id`: String,
    val `workspace_id`: String,
    val `kind`: String,
    val `title`: String,
    val `thread_id`: String? = null,
    val `terminal_id`: String? = null,
    val `status`: String = "idle",
    val `attention`: Boolean = false,
    val `started_at_ms`: Long? = null,
    val `can_stop`: Boolean = false,
    val `attention_kind`: String? = null,
)

@Serializable
data class ThreadSummary(
    val `workspace_id`: String,
    val `thread_id`: String,
    val `title`: String,
    val `provider`: String,
    val `model`: String?,
    val `cwd`: String?,
    val `open`: Boolean,
    val `archived`: Boolean,
    val `last_activity_at_ms`: Long?,
    val `status`: String,
    val `history_bucket`: String,
)

@Serializable
data class Workspace(
    val `workspace_id`: String,
    val `label`: String,
    val `path`: String,
    val `open`: Boolean,
    val `panes`: List<Pane>,
    val `threads`: List<ThreadSummary>,
)

@Serializable
data class PushOpenKey(
    val `host_id`: String,
    val `record_base64`: String,
)

@Serializable
data class PushOpenRequest(
    val `api_version`: Long,
    val `envelope`: String,
    val `keys`: List<PushOpenKey>,
    val `recent`: List<String>? = null,
)

@Serializable
data class PushNotification(
    val `api_version`: Long,
    val `opened`: Boolean,
    val `update_required`: Boolean,
    val `error`: String?,
    val `host_id`: String?,
    val `workspace_id`: String?,
    val `thread_id`: String?,
    val `turn_id`: String?,
    val `kind`: String,
    val `attention`: String?,
    val `channel`: String,
    val `title`: String,
    val `body`: String,
    val `deep_link`: String,
    val `actions`: List<String>,
    val `dedupe_key`: String?,
    val `duplicate`: Boolean,
)

@Serializable
enum class AttentionKind {
    `unread`,
    `needs_approval`,
    `blocked`,
    `failed`,
}

@Serializable
enum class FileKind {
    `file`,
    `preview`,
}

@Serializable
enum class AttentionStatus {
    `idle`,
    `working`,
    `done`,
    `waiting`,
    `error`,
}

@Serializable
data class AttentionItem(
    val `workspace_id`: String,
    val `thread_id`: String,
    val `turn_id`: String?,
    val `kind`: AttentionKind,
    val `status`: AttentionStatus,
    val `since_ms`: Long,
    val `title`: String,
    val `deep_link`: String,
)

@Serializable
data class AttentionView(
    val `items`: List<AttentionItem>,
    val `count`: Long,
    val `loading`: Boolean,
)

@Serializable
data class AttentionQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: AttentionView?,
    val `error`: LocalError?,
)

@Serializable
data class ManageBusy(
    val `pending_turns`: Long = 0,
    val `running_tasks`: Long = 0,
)

@Serializable
data class ManageJob(
    val `intent_id`: String,
    val `kind`: String,
    val `state`: String = "pending",
    val `workspace_id`: String? = null,
    val `thread_id`: String? = null,
    val `busy`: ManageBusy? = null,
    val `error`: LocalError? = null,
)

@Serializable
data class ManageDirectoryEntry(
    val `name`: String,
    val `path`: String,
)

@Serializable
data class ManageDirectory(
    val `path`: String = "",
    val `parent`: String? = null,
    val `entries`: List<ManageDirectoryEntry> = emptyList(),
    val `suggestions`: List<String> = emptyList(),
    val `supported`: Boolean = false,
    val `loading`: Boolean = false,
    val `error`: LocalError? = null,
)

@Serializable
data class ManageNewChat(
    val `workspace_id`: String? = null,
    val `selection`: ChatSelection,
    val `providers`: List<ChatChoice> = emptyList(),
    val `catalogs`: ChatCatalogs,
    val `loading`: Boolean = false,
    val `can_create`: Boolean = false,
    val `error`: LocalError? = null,
)

@Serializable
data class ManageView(
    val `operations`: List<ManageJob>,
    val `directory`: ManageDirectory,
    val `new_chat`: ManageNewChat,
    val `can_manage_workspaces`: Boolean,
    val `can_create_threads`: Boolean,
)

@Serializable
data class ManageQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: ManageView?,
    val `error`: LocalError?,
)
