// Generated by `mise run mobile-models-generate`. DO NOT EDIT.
package dev.verdeai.core

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement

// Encode Event/Effect through their sealed base type to include the discriminator.
val CoreJson = Json { ignoreUnknownKeys = true; encodeDefaults = true; explicitNulls = true }

@Serializable
data class Config(
    val `api_version`: Long,
    val `host_id`: String,
    val `label`: String,
    val `https_url`: String?,
    val `wss_url`: String?,
    val `client_revision`: Long,
    val `session_nonce`: String,
    val `jitter_seed`: ULong,
)

@Serializable
enum class Lifecycle {
    `created`,
    `foreground`,
    `background`,
    `stopped`,
}

@Serializable
data class LocalError(
    val `domain`: String = "input",
    val `code`: String,
    val `message`: String,
    val `failure_kind`: String? = null,
    val `retryable`: Boolean = false,
    val `retry_after_ms`: Long? = null,
    val `intent_id`: String? = null,
    val `rpc_code`: String? = null,
    val `delivery`: String? = "rejected",
)

@Serializable
data class Operation(
    val `intent_id`: String,
    val `state`: String = "failed",
    val `error`: LocalError?,
)

@Serializable
enum class TransportFailureKind {
    `network`,
    `timeout`,
    `cancelled`,
    `tls`,
    `server_unavailable`,
    `resource`,
}

@Serializable
enum class TransportFailureCode {
    `unknown`,
    `offline`,
    `dns`,
    `refused`,
    `reset`,
    `timeout`,
    `cancelled`,
    `certificate`,
    `hostname`,
    `pin_mismatch`,
    `unavailable`,
    `resource`,
}

@Serializable
data class TransportFailure(
    val `kind`: TransportFailureKind,
    val `code`: TransportFailureCode,
)

@Serializable
enum class PlatformFailureCode {
    `unavailable`,
    `locked`,
    `denied`,
    `io`,
    `resource`,
}

@Serializable
data class PlatformFailure(
    val `code`: PlatformFailureCode,
)

@Serializable
data class Header(
    val `name`: String,
    val `value`: String,
)

@Serializable
data class Tls(
    val `origin`: String,
    val `spki_sha256`: String,
)

@Serializable
data class VtModes(
    val `application_cursor`: Boolean,
    val `bracketed_paste`: Boolean,
)

@Serializable
data class AttachmentInput(
    val `local_id`: String,
    val `name`: String,
    val `mime`: String,
    val `byte_size`: String,
    val `bytes_base64`: String,
)

@Serializable
sealed class Event

@Serializable
@SerialName("start")
data class EventStart(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `foreground`: Boolean,
    val `network_available`: Boolean,
) : Event()

@Serializable
@SerialName("foreground")
data class EventForeground(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
) : Event()

@Serializable
@SerialName("background")
data class EventBackground(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
) : Event()

@Serializable
@SerialName("shutdown")
data class EventShutdown(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
) : Event()

@Serializable
@SerialName("network_changed")
data class EventNetworkChanged(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `available`: Boolean,
    val `network_id`: String,
) : Event()

@Serializable
@SerialName("http_response")
data class EventHttpResponse(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `status`: Int?,
    val `headers`: List<Header>,
    val `body_base64`: String?,
    val `error`: TransportFailure?,
) : Event()

@Serializable
@SerialName("ws_open")
data class EventWsOpen(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `socket_id`: String,
    val `generation`: String,
    val `protocol`: String,
) : Event()

@Serializable
@SerialName("ws_message")
data class EventWsMessage(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `socket_id`: String,
    val `generation`: String,
    val `text`: String,
) : Event()

@Serializable
@SerialName("ws_closed")
data class EventWsClosed(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `socket_id`: String,
    val `generation`: String,
    val `code`: Int?,
    val `clean`: Boolean,
    val `error`: TransportFailure?,
) : Event()

@Serializable
@SerialName("timer_fired")
data class EventTimerFired(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `timer_id`: String,
    val `generation`: String,
) : Event()

@Serializable
@SerialName("secure_store_value")
data class EventSecureStoreValue(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
    val `value_base64`: String?,
    val `error`: PlatformFailure?,
) : Event()

@Serializable
@SerialName("secure_store_done")
data class EventSecureStoreDone(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
    val `error`: PlatformFailure?,
) : Event()

@Serializable
@SerialName("tls_peer")
data class EventTlsPeer(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `origin`: String,
    val `spki_sha256`: String,
    val `system_trusted`: Boolean,
) : Event()

@Serializable
@SerialName("terminal_applied")
data class EventTerminalApplied(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `effect_id`: String,
    val `generation`: String,
    val `terminal_id`: String,
    val `grid_revision`: String,
    val `error`: PlatformFailure?,
) : Event()

@Serializable
@SerialName("terminal_reply")
data class EventTerminalReply(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `terminal_id`: String,
    val `bytes_base64`: String,
) : Event()

@Serializable
@SerialName("pair")
data class EventPair(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `link`: String,
    val `device_label`: String,
    val `client_nonce`: String,
) : Event()

@Serializable
@SerialName("trust_decision")
data class EventTrustDecision(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `proposal_id`: String,
    val `accept`: Boolean,
) : Event()

@Serializable
@SerialName("retry_connection")
data class EventRetryConnection(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
) : Event()

@Serializable
@SerialName("focus")
data class EventFocus(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String?,
    val `thread_id`: String?,
    val `terminal_id`: String?,
) : Event()

@Serializable
@SerialName("history_search")
data class EventHistorySearch(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `query`: String,
    val `workspace_id`: String?,
) : Event()

@Serializable
@SerialName("history_load_more")
data class EventHistoryLoadMore(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
) : Event()

@Serializable
@SerialName("shell_confirm")
data class EventShellConfirm(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `confirmation_id`: String,
    val `accept`: Boolean,
) : Event()

@Serializable
@SerialName("terminal_create")
data class EventTerminalCreate(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `cwd`: String?,
    val `cols`: Int,
    val `rows`: Int,
) : Event()

@Serializable
@SerialName("thread_open")
data class EventThreadOpen(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
) : Event()

@Serializable
@SerialName("thread_load_older")
data class EventThreadLoadOlder(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
) : Event()

@Serializable
@SerialName("draft_set")
data class EventDraftSet(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `text`: String,
    val `attachments`: List<AttachmentInput>,
) : Event()

@Serializable
@SerialName("composer_select")
data class EventComposerSelect(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `provider`: String?,
    val `model`: String?,
    val `effort`: String?,
    val `access`: String?,
    val `speed`: String?,
) : Event()

@Serializable
@SerialName("send")
data class EventSend(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `draft_revision`: String,
) : Event()

@Serializable
@SerialName("turn_cancel")
data class EventTurnCancel(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `turn_id`: String,
) : Event()

@Serializable
enum class EventFollowupSubmitKind {
    `queue`,
    `steer`,
}

@Serializable
@SerialName("followup_submit")
data class EventFollowupSubmit(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `draft_revision`: String,
    val `kind`: EventFollowupSubmitKind,
) : Event()

@Serializable
@SerialName("followup_retry")
data class EventFollowupRetry(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `followup_id`: String,
) : Event()

@Serializable
@SerialName("followup_pull_back")
data class EventFollowupPullBack(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `followup_id`: String,
) : Event()

@Serializable
@SerialName("followup_cancel")
data class EventFollowupCancel(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `followup_id`: String,
) : Event()

@Serializable
enum class EventApprovalDecideDecision {
    `approve`,
    `deny`,
}

@Serializable
@SerialName("approval_decide")
data class EventApprovalDecide(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `turn_id`: String,
    val `call_id`: String,
    val `decision`: EventApprovalDecideDecision,
) : Event()

@Serializable
@SerialName("shell_prepare")
data class EventShellPrepare(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `command`: String,
) : Event()

@Serializable
@SerialName("slash_search")
data class EventSlashSearch(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `query`: String,
) : Event()

@Serializable
@SerialName("slash_run")
data class EventSlashRun(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `command`: String,
    val `args`: String,
) : Event()

@Serializable
@SerialName("mention_search")
data class EventMentionSearch(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `workspace_id`: String,
    val `thread_id`: String,
    val `query`: String,
) : Event()

@Serializable
@SerialName("terminal_attach")
data class EventTerminalAttach(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
) : Event()

@Serializable
@SerialName("terminal_detach")
data class EventTerminalDetach(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
) : Event()

@Serializable
@SerialName("terminal_kill")
data class EventTerminalKill(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
) : Event()

@Serializable
@SerialName("terminal_resize")
data class EventTerminalResize(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
    val `cols`: Int,
    val `rows`: Int,
) : Event()

@Serializable
enum class EventTerminalInputInputKind {
    `text`,
    `key`,
    `paste`,
}

@Serializable
data class EventTerminalInputInput(
    val `kind`: EventTerminalInputInputKind,
    val `text`: String? = null,
    val `key`: String? = null,
    val `ctrl`: Boolean,
    val `alt`: Boolean,
    val `shift`: Boolean,
)

@Serializable
@SerialName("terminal_input")
data class EventTerminalInput(
    val `api_version`: Long = 1,
    val `now_ms`: Long,
    val `wall_time_ms`: Long,
    val `intent_id`: String,
    val `terminal_id`: String,
    val `vt_modes`: VtModes,
    val `input`: EventTerminalInputInput,
) : Event()

@Serializable
sealed class Effect

@Serializable
@SerialName("http_request")
data class EffectHttpRequest(
    val `effect_id`: String,
    val `generation`: String,
    val `method`: String,
    val `url`: String,
    val `headers`: List<Header>,
    val `body_base64`: String?,
    val `timeout_ms`: Long,
    val `max_response_bytes`: Long,
    val `tls`: Tls,
) : Effect()

@Serializable
@SerialName("http_cancel")
data class EffectHttpCancel(
    val `effect_id`: String,
    val `generation`: String,
    val `request_id`: String,
) : Effect()

@Serializable
@SerialName("ws_open")
data class EffectWsOpen(
    val `effect_id`: String,
    val `generation`: String,
    val `url`: String,
    val `protocols`: List<String>,
    val `tls`: Tls,
    val `max_message_bytes`: Long,
) : Effect()

@Serializable
@SerialName("ws_send")
data class EffectWsSend(
    val `effect_id`: String,
    val `generation`: String,
    val `socket_id`: String,
    val `text`: String,
) : Effect()

@Serializable
@SerialName("ws_close")
data class EffectWsClose(
    val `effect_id`: String,
    val `generation`: String,
    val `socket_id`: String,
    val `code`: Int,
) : Effect()

@Serializable
@SerialName("set_timer")
data class EffectSetTimer(
    val `effect_id`: String,
    val `generation`: String,
    val `timer_id`: String,
    val `delay_ms`: Long,
    val `purpose`: String,
) : Effect()

@Serializable
@SerialName("cancel_timer")
data class EffectCancelTimer(
    val `effect_id`: String,
    val `generation`: String,
    val `timer_id`: String,
) : Effect()

@Serializable
@SerialName("secure_store_get")
data class EffectSecureStoreGet(
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
) : Effect()

@Serializable
@SerialName("secure_store_put")
data class EffectSecureStorePut(
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
    val `value_base64`: String,
) : Effect()

@Serializable
@SerialName("secure_store_delete")
data class EffectSecureStoreDelete(
    val `effect_id`: String,
    val `generation`: String,
    val `key`: String,
) : Effect()

@Serializable
@SerialName("state_changed")
data class EffectStateChanged(
    val `effect_id`: String,
    val `generation`: String,
    val `revision`: String,
    val `scopes`: List<String>,
) : Effect()

@Serializable
data class EffectNotifyTarget(
    val `host_id`: String,
    val `workspace_id`: String?,
    val `thread_id`: String?,
)

@Serializable
@SerialName("notify")
data class EffectNotify(
    val `effect_id`: String,
    val `generation`: String,
    val `notification_id`: String,
    val `kind`: String,
    val `title`: String,
    val `body`: String,
    val `target`: EffectNotifyTarget,
    val `actions`: List<String>,
) : Effect()

@Serializable
@SerialName("log")
data class EffectLog(
    val `effect_id`: String,
    val `generation`: String,
    val `level`: String,
    val `code`: String,
    val `fields`: JsonElement,
) : Effect()

@Serializable
@SerialName("tls_probe")
data class EffectTlsProbe(
    val `effect_id`: String,
    val `generation`: String,
    val `origin`: String,
) : Effect()

@Serializable
@SerialName("terminal_output")
data class EffectTerminalOutput(
    val `effect_id`: String,
    val `generation`: String,
    val `terminal_id`: String,
    val `reset`: Boolean,
    val `bytes_base64`: String,
    val `next_offset`: String,
) : Effect()

@Serializable
data class EffectBatch(
    val `api_version`: Long,
    val `revision`: String,
    val `effects`: List<Effect>,
)

@Serializable
data class TrustProposal(
    val `id`: String,
    val `origin`: String,
    val `spki_sha256`: String,
    val `runtime_id`: String?,
)

@Serializable
data class HostView(
    val `host_id`: String,
    val `label`: String,
    val `https_url`: String?,
    val `runtime_id`: String?,
    val `instance_id`: String?,
    val `phase`: String,
    val `lifecycle`: Lifecycle,
    val `auth_state`: String,
    val `sync_state`: String,
    val `capabilities`: List<String>,
    val `scopes`: List<String>,
    val `retry_at_ms`: Long?,
    val `trust_proposal`: TrustProposal?,
    val `update_required`: Boolean,
    val `error`: LocalError?,
)

@Serializable
data class HostsView(
    val `items`: List<HostView>,
    val `operations`: List<Operation>,
)

@Serializable
data class HomeView(
    val `items`: List<JsonElement>,
    val `loading`: Boolean,
    val `stale`: Boolean,
    val `incomplete_scopes`: List<String>,
    val `error`: LocalError?,
)

@Serializable
data class HistoryView(
    val `query`: String,
    val `items`: List<JsonElement>,
    val `next_cursor`: String?,
    val `loading`: Boolean,
    val `error`: LocalError?,
)

@Serializable
data class WorkspacesView(
    val `items`: List<JsonElement>,
    val `loading`: Boolean,
    val `stale`: Boolean,
    val `error`: LocalError?,
    val `history`: HistoryView,
)

@Serializable
data class HostsQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: HostsView?,
    val `error`: LocalError?,
)

@Serializable
data class HomeQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: HomeView?,
    val `error`: LocalError?,
)

@Serializable
data class WorkspacesQuery(
    val `api_version`: Long,
    val `revision`: String,
    val `data`: WorkspacesView?,
    val `error`: LocalError?,
)
