//! User-scoped MCP registration for agent providers launched inside Verde.

const std = @import("std");
const builtin = @import("builtin");
const platform_paths = @import("platform_paths");
const mcp_endpoint = @import("../mcp/endpoint.zig");
const process_env = @import("../platform/env.zig");
const providers_protocol = @import("headless").providers_protocol;

const log = std.log.scoped(.provider_mcp);

const MANAGED_ENV_KEY = "VERDE_MCP_MANAGED";
const MANAGED_ENV_VALUE = "1";
const MANAGED_HEADER_KEY = "X-Verde-MCP-Managed";
const CLIENT_HEADER_KEY = "X-Verde-MCP-Client";
const CODEX_BLOCK_BEGIN = "# >>> verde managed mcp >>>";
const CODEX_BLOCK_END = "# <<< verde managed mcp <<<";
const GROK_BLOCK_BEGIN = "# >>> verde managed mcp >>>";
const GROK_BLOCK_END = "# <<< verde managed mcp <<<";
const PI_MARKER = "// Verde managed MCP integration. Do not edit this file; disable it from Verde settings.\n";
const LEGACY_FX_MARKER = "verde-managed-mcp-v2\n";
const MAX_CONFIG_BYTES = 8 * 1024 * 1024;

pub const Provider = providers_protocol.IntegrationProvider;

pub const Endpoint = mcp_endpoint.Endpoint;

pub const HttpConnection = struct {
    url: []u8,
    authorization: []u8,

    pub fn deinit(self: *HttpConnection, allocator: std.mem.Allocator) void {
        allocator.free(self.url);
        allocator.free(self.authorization);
        self.* = undefined;
    }
};

/// Loads the daemon's authenticated loopback endpoint for provider-specific
/// runtime injection. The registration marker remains the opt-in authority.
pub fn loadEndpoint(allocator: std.mem.Allocator) !?Endpoint {
    const pref_path = try platform_paths.sdlPrefPathFallback(allocator, "verde", "Native");
    defer allocator.free(pref_path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    return mcp_endpoint.load(allocator, threaded.io(), pref_path);
}

pub fn loadHttpConnection(allocator: std.mem.Allocator) !?HttpConnection {
    var endpoint = (try loadEndpoint(allocator)) orelse return null;
    defer endpoint.deinit(allocator);
    const url = try endpoint.urlAlloc(allocator);
    errdefer allocator.free(url);
    return .{
        .url = url,
        .authorization = try endpoint.authorizationAlloc(allocator),
    };
}

const ALL_PROVIDERS = [_]Provider{ .codex, .claude, .cursor, .opencode, .amp, .pi, .fx, .grok };

pub const RegistrationStatus = providers_protocol.RegistrationStatus;
pub const Summary = providers_protocol.McpSummary;

const JsonSpec = struct {
    relative_path: []const u8,
    section_key: []const u8,
    environment_key: []const u8,
    remote_type: ?[]const u8 = null,
    enabled_key: ?[]const u8 = null,
    disable_oauth: bool = false,
    bearer_token_env: ?[]const u8 = null,
};

const CLAUDE_SPEC: JsonSpec = .{
    .relative_path = ".claude.json",
    .section_key = "mcpServers",
    .environment_key = "env",
    .remote_type = "http",
};
const CURSOR_SPEC: JsonSpec = .{
    .relative_path = ".cursor/mcp.json",
    .section_key = "mcpServers",
    .environment_key = "env",
};
const OPENCODE_SPEC: JsonSpec = .{
    .relative_path = ".config/opencode/opencode.json",
    .section_key = "mcp",
    .environment_key = "environment",
    .remote_type = "remote",
    .enabled_key = "enabled",
    .disable_oauth = true,
};
const AMP_SPEC: JsonSpec = .{
    .relative_path = ".config/amp/settings.json",
    .section_key = "amp.mcpServers",
    .environment_key = "env",
};
const FX_SPEC: JsonSpec = .{
    .relative_path = ".fx/mcp.json",
    .section_key = "mcp",
    .environment_key = "environment",
    .remote_type = "http",
    .enabled_key = "enabled",
    // FX rejects a literal Authorization header. It reads the raw token from
    // this variable and constructs the Bearer header itself.
    .bearer_token_env = "VERDE_MCP_TOKEN",
};

/// Returns the current registration state for every provider installed on PATH.
pub fn inspect(allocator: std.mem.Allocator) Summary {
    const home = platform_paths.userHome(allocator) catch return .{};
    defer allocator.free(home);
    return inspectAtHome(allocator, home);
}

/// Returns whether Verde owns the selected provider's current MCP entry.
pub fn isInstalled(allocator: std.mem.Allocator, provider: Provider) bool {
    const home = platform_paths.userHome(allocator) catch return false;
    defer allocator.free(home);
    return inspectProviderAtHome(allocator, home, provider) == .installed;
}

/// Installs or refreshes Verde's user-scoped MCP entry for every detected provider.
pub fn install(allocator: std.mem.Allocator) !Summary {
    const home = try platform_paths.userHome(allocator);
    defer allocator.free(home);
    const pref_path = try platform_paths.sdlPrefPathFallback(allocator, "verde", "Native");
    defer allocator.free(pref_path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    var endpoint = if (try mcp_endpoint.load(allocator, threaded.io(), pref_path)) |existing|
        existing
    else
        try mcp_endpoint.loadOrCreateForPort(allocator, threaded.io(), pref_path, mcp_endpoint.DEFAULT_PORT);
    defer endpoint.deinit(allocator);
    return installAtHome(allocator, home, &endpoint, detectedProvidersAtHome(allocator, home));
}

/// Removes only MCP entries carrying Verde's ownership marker.
pub fn uninstall(allocator: std.mem.Allocator) !Summary {
    const home = try platform_paths.userHome(allocator);
    defer allocator.free(home);
    var failed = [_]bool{false} ** ALL_PROVIDERS.len;
    for (ALL_PROVIDERS, 0..) |provider, index| {
        removeProviderAtHome(allocator, home, provider) catch |err| {
            log.warn("failed to remove {s} MCP registration: {s}", .{ @tagName(provider), @errorName(err) });
            failed[index] = true;
        };
    }
    var summary = inspectAtHome(allocator, home);
    for (ALL_PROVIDERS, 0..) |provider, index| {
        if (failed[index]) setSummaryStatus(&summary, provider, .failed);
    }
    return summary;
}

fn detectedProvidersAtHome(allocator: std.mem.Allocator, home: []const u8) [ALL_PROVIDERS.len]bool {
    var detected = [ALL_PROVIDERS.len]bool{
        process_env.commandExists("codex"),
        process_env.commandExists("claude"),
        process_env.commandExists("agent") or process_env.commandExists("cursor-agent"),
        process_env.commandExists("opencode"),
        process_env.commandExists("amp"),
        process_env.commandExists("pi"),
        process_env.commandExists("fx"),
        process_env.commandExists("grok"),
    };
    for (ALL_PROVIDERS, 0..) |provider, index| {
        detected[index] = detected[index] or providerConfigExistsAtHome(allocator, home, provider);
    }
    return detected;
}

fn inspectAtHome(allocator: std.mem.Allocator, home: []const u8) Summary {
    const detected = detectedProvidersAtHome(allocator, home);
    var summary: Summary = .{};
    for (ALL_PROVIDERS, 0..) |provider, index| {
        const status = inspectProviderAtHome(allocator, home, provider);
        setSummaryStatus(&summary, provider, if (!detected[index] and status == .not_installed) .unavailable else status);
    }
    return summary;
}

fn providerConfigExistsAtHome(allocator: std.mem.Allocator, home: []const u8, provider: Provider) bool {
    const relative_path = switch (provider) {
        .codex => ".codex/config.toml",
        .claude => CLAUDE_SPEC.relative_path,
        .cursor => CURSOR_SPEC.relative_path,
        .opencode => OPENCODE_SPEC.relative_path,
        .amp => AMP_SPEC.relative_path,
        .pi => ".pi/agent/extensions/verde-mcp.ts",
        .fx => FX_SPEC.relative_path,
        .grok => ".grok/config.toml",
    };
    const path = configPathAlloc(allocator, home, relative_path) catch return false;
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    std.Io.Dir.cwd().access(threaded.io(), path, .{}) catch return false;
    return true;
}

fn installAtHome(
    allocator: std.mem.Allocator,
    home: []const u8,
    endpoint: *const mcp_endpoint.Endpoint,
    detected: [ALL_PROVIDERS.len]bool,
) !Summary {
    var failed = [_]bool{false} ** ALL_PROVIDERS.len;
    for (ALL_PROVIDERS, 0..) |provider, index| {
        if (!detected[index]) continue;
        installProviderAtHome(allocator, home, endpoint, provider) catch |err| switch (err) {
            error.ProviderMcpConflict => continue,
            else => {
                log.warn("failed to install {s} MCP registration: {s}", .{ @tagName(provider), @errorName(err) });
                failed[index] = true;
                continue;
            },
        };
    }

    var summary: Summary = .{};
    for (ALL_PROVIDERS, 0..) |provider, index| {
        const status = inspectProviderAtHome(allocator, home, provider);
        setSummaryStatus(&summary, provider, if (failed[index])
            .failed
        else if (!detected[index] and status == .not_installed)
            .unavailable
        else
            status);
    }
    return summary;
}

fn setSummaryStatus(summary: *Summary, provider: Provider, status: RegistrationStatus) void {
    switch (provider) {
        .codex => summary.codex = status,
        .claude => summary.claude = status,
        .cursor => summary.cursor = status,
        .opencode => summary.opencode = status,
        .amp => summary.amp = status,
        .pi => summary.pi = status,
        .fx => summary.fx = status,
        .grok => summary.grok = status,
    }
}

fn installProviderAtHome(allocator: std.mem.Allocator, home: []const u8, endpoint: *const mcp_endpoint.Endpoint, provider: Provider) !void {
    return switch (provider) {
        .codex => installCodexAtHome(allocator, home, endpoint),
        .claude => installJsonAtHome(allocator, home, endpoint, .claude, CLAUDE_SPEC),
        .cursor => installJsonAtHome(allocator, home, endpoint, .cursor, CURSOR_SPEC),
        .opencode => installJsonAtHome(allocator, home, endpoint, .opencode, OPENCODE_SPEC),
        .amp => installJsonAtHome(allocator, home, endpoint, .amp, AMP_SPEC),
        .pi => installPiAtHome(allocator, home, endpoint),
        .fx => installFxAtHome(allocator, home, endpoint),
        .grok => installGrokAtHome(allocator, home, endpoint),
    };
}

fn removeProviderAtHome(allocator: std.mem.Allocator, home: []const u8, provider: Provider) !void {
    return switch (provider) {
        .codex => removeCodexAtHome(allocator, home),
        .claude => removeJsonAtHome(allocator, home, CLAUDE_SPEC),
        .cursor => removeJsonAtHome(allocator, home, CURSOR_SPEC),
        .opencode => removeJsonAtHome(allocator, home, OPENCODE_SPEC),
        .amp => removeJsonAtHome(allocator, home, AMP_SPEC),
        .pi => removePiAtHome(allocator, home),
        .fx => removeFxAtHome(allocator, home),
        .grok => removeGrokAtHome(allocator, home),
    };
}

fn inspectProviderAtHome(allocator: std.mem.Allocator, home: []const u8, provider: Provider) RegistrationStatus {
    return switch (provider) {
        .codex => inspectCodexAtHome(allocator, home),
        .claude => inspectJsonAtHome(allocator, home, CLAUDE_SPEC),
        .cursor => inspectJsonAtHome(allocator, home, CURSOR_SPEC),
        .opencode => inspectJsonAtHome(allocator, home, OPENCODE_SPEC),
        .amp => inspectJsonAtHome(allocator, home, AMP_SPEC),
        .pi => inspectPiAtHome(allocator, home),
        .fx => inspectJsonAtHome(allocator, home, FX_SPEC),
        .grok => inspectGrokAtHome(allocator, home),
    };
}

fn configPathAlloc(allocator: std.mem.Allocator, home: []const u8, relative_path: []const u8) ![]u8 {
    return std.fs.path.join(allocator, &.{ home, relative_path });
}

fn readFileIfPresent(allocator: std.mem.Allocator, io: std.Io, path: []const u8) !?[]u8 {
    return std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .limited(MAX_CONFIG_BYTES)) catch |err| switch (err) {
        error.FileNotFound => null,
        else => return err,
    };
}

fn ensureParentDir(io: std.Io, path: []const u8) !void {
    const dir = std.fs.path.dirname(path) orelse return;
    std.Io.Dir.cwd().access(io, dir, .{}) catch |err| switch (err) {
        error.FileNotFound => try std.Io.Dir.cwd().createDirPath(io, dir),
        else => return err,
    };
}

fn writeFileAtomic(allocator: std.mem.Allocator, io: std.Io, path: []const u8, content: []const u8) !void {
    try ensureParentDir(io, path);
    const tmp_path = try std.fmt.allocPrint(allocator, "{s}.verde-mcp.tmp", .{path});
    defer allocator.free(tmp_path);
    {
        const private_permissions: std.Io.File.Permissions = if (builtin.os.tag == .windows)
            .default_file
        else
            @enumFromInt(0o600);
        var file = try std.Io.Dir.cwd().createFile(io, tmp_path, .{ .permissions = private_permissions });
        defer file.close(io);
        try file.writeStreamingAll(io, content);
    }
    try std.Io.Dir.cwd().rename(tmp_path, std.Io.Dir.cwd(), path, io);
}

fn inspectCodexAtHome(allocator: std.mem.Allocator, home: []const u8) RegistrationStatus {
    const path = configPathAlloc(allocator, home, ".codex/config.toml") catch return .not_installed;
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const content = readFileIfPresent(allocator, threaded.io(), path) catch return .conflict;
    defer if (content) |bytes| allocator.free(bytes);
    const bytes = content orelse return .not_installed;
    if (std.mem.indexOf(u8, bytes, CODEX_BLOCK_BEGIN) != null and std.mem.indexOf(u8, bytes, CODEX_BLOCK_END) != null) return .installed;
    if (std.mem.indexOf(u8, bytes, "[mcp_servers.verde]") != null) return .conflict;
    return .not_installed;
}

fn installCodexAtHome(allocator: std.mem.Allocator, home: []const u8, endpoint: *const Endpoint) !void {
    const path = try configPathAlloc(allocator, home, ".codex/config.toml");
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const existing = try readFileIfPresent(allocator, io, path);
    defer if (existing) |bytes| allocator.free(bytes);
    const content = existing orelse "";
    if (std.mem.indexOf(u8, content, "[mcp_servers.verde]") != null and std.mem.indexOf(u8, content, CODEX_BLOCK_BEGIN) == null) {
        return error.ProviderMcpConflict;
    }
    const without_block = try removeCodexBlockAlloc(allocator, content);
    defer allocator.free(without_block);
    const url = try endpoint.urlAlloc(allocator);
    defer allocator.free(url);
    const authorization = try endpoint.authorizationAlloc(allocator);
    defer allocator.free(authorization);
    const encoded_url = try std.json.Stringify.valueAlloc(allocator, url, .{});
    defer allocator.free(encoded_url);
    const encoded_authorization = try std.json.Stringify.valueAlloc(allocator, authorization, .{});
    defer allocator.free(encoded_authorization);
    const separator = if (without_block.len == 0 or without_block[without_block.len - 1] == '\n') "" else "\n";
    const updated = try std.fmt.allocPrint(
        allocator,
        "{s}{s}{s}\n[mcp_servers.verde]\nurl = {s}\nhttp_headers = {{ Authorization = {s}, \"{s}\" = \"codex\", \"{s}\" = \"{s}\" }}\ndefault_tools_approval_mode = \"approve\"\n{s}\n",
        .{ without_block, separator, CODEX_BLOCK_BEGIN, encoded_url, encoded_authorization, CLIENT_HEADER_KEY, MANAGED_HEADER_KEY, MANAGED_ENV_VALUE, CODEX_BLOCK_END },
    );
    defer allocator.free(updated);
    try writeFileAtomic(allocator, io, path, updated);
}

fn removeCodexAtHome(allocator: std.mem.Allocator, home: []const u8) !void {
    const path = try configPathAlloc(allocator, home, ".codex/config.toml");
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const existing = try readFileIfPresent(allocator, io, path) orelse return;
    defer allocator.free(existing);
    const updated = try removeCodexBlockAlloc(allocator, existing);
    defer allocator.free(updated);
    if (updated.len != existing.len) try writeFileAtomic(allocator, io, path, updated);
}

fn removeCodexBlockAlloc(allocator: std.mem.Allocator, content: []const u8) ![]u8 {
    const begin = std.mem.indexOf(u8, content, CODEX_BLOCK_BEGIN) orelse return allocator.dupe(u8, content);
    const end_start = std.mem.indexOfPos(u8, content, begin, CODEX_BLOCK_END) orelse return allocator.dupe(u8, content);
    var end = end_start + CODEX_BLOCK_END.len;
    if (end < content.len and content[end] == '\r') end += 1;
    if (end < content.len and content[end] == '\n') end += 1;
    var writer: std.Io.Writer.Allocating = .init(allocator);
    errdefer writer.deinit();
    try writer.writer.writeAll(content[0..begin]);
    try writer.writer.writeAll(content[end..]);
    return writer.toOwnedSlice();
}

fn inspectGrokAtHome(allocator: std.mem.Allocator, home: []const u8) RegistrationStatus {
    const path = configPathAlloc(allocator, home, ".grok/config.toml") catch return .not_installed;
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const content = readFileIfPresent(allocator, threaded.io(), path) catch return .conflict;
    defer if (content) |bytes| allocator.free(bytes);
    const bytes = content orelse return .not_installed;
    if (std.mem.indexOf(u8, bytes, GROK_BLOCK_BEGIN) != null and std.mem.indexOf(u8, bytes, GROK_BLOCK_END) != null) return .installed;
    if (std.mem.indexOf(u8, bytes, "[mcp_servers.verde]") != null) return .conflict;
    return .not_installed;
}

fn installGrokAtHome(allocator: std.mem.Allocator, home: []const u8, endpoint: *const Endpoint) !void {
    const path = try configPathAlloc(allocator, home, ".grok/config.toml");
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const existing = try readFileIfPresent(allocator, io, path);
    defer if (existing) |bytes| allocator.free(bytes);
    const content = existing orelse "";
    if (std.mem.indexOf(u8, content, "[mcp_servers.verde]") != null and std.mem.indexOf(u8, content, GROK_BLOCK_BEGIN) == null) {
        return error.ProviderMcpConflict;
    }
    const without_block = try removeCodexBlockAlloc(allocator, content);
    defer allocator.free(without_block);
    const url = try endpoint.urlAlloc(allocator);
    defer allocator.free(url);
    const authorization = try endpoint.authorizationAlloc(allocator);
    defer allocator.free(authorization);
    const encoded_url = try std.json.Stringify.valueAlloc(allocator, url, .{});
    defer allocator.free(encoded_url);
    const encoded_authorization = try std.json.Stringify.valueAlloc(allocator, authorization, .{});
    defer allocator.free(encoded_authorization);
    const separator = if (without_block.len == 0 or without_block[without_block.len - 1] == '\n') "" else "\n";
    const updated = try std.fmt.allocPrint(
        allocator,
        "{s}{s}{s}\n[mcp_servers.verde]\nurl = {s}\nheaders = {{ Authorization = {s}, \"{s}\" = \"grok\", \"{s}\" = \"{s}\" }}\nenabled = true\n{s}\n",
        .{ without_block, separator, GROK_BLOCK_BEGIN, encoded_url, encoded_authorization, CLIENT_HEADER_KEY, MANAGED_HEADER_KEY, MANAGED_ENV_VALUE, GROK_BLOCK_END },
    );
    defer allocator.free(updated);
    try writeFileAtomic(allocator, io, path, updated);
}

fn removeGrokAtHome(allocator: std.mem.Allocator, home: []const u8) !void {
    const path = try configPathAlloc(allocator, home, ".grok/config.toml");
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const existing = try readFileIfPresent(allocator, io, path) orelse return;
    defer allocator.free(existing);
    const updated = try removeCodexBlockAlloc(allocator, existing);
    defer allocator.free(updated);
    if (updated.len != existing.len) try writeFileAtomic(allocator, io, path, updated);
}

fn inspectPiAtHome(allocator: std.mem.Allocator, home: []const u8) RegistrationStatus {
    return inspectManagedFileAtHome(allocator, home, ".pi/agent/extensions/verde-mcp.ts", PI_MARKER);
}

fn installPiAtHome(allocator: std.mem.Allocator, home: []const u8, endpoint: *const Endpoint) !void {
    const path = try configPathAlloc(allocator, home, ".pi/agent/extensions/verde-mcp.ts");
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    if (try readFileIfPresent(allocator, io, path)) |existing| {
        defer allocator.free(existing);
        if (!std.mem.startsWith(u8, existing, PI_MARKER)) return error.ProviderMcpConflict;
    }
    const source = try piExtensionAlloc(allocator, endpoint);
    defer allocator.free(source);
    try writeFileAtomic(allocator, io, path, source);
}

fn removePiAtHome(allocator: std.mem.Allocator, home: []const u8) !void {
    return removeManagedFileAtHome(allocator, home, ".pi/agent/extensions/verde-mcp.ts", PI_MARKER);
}

fn piExtensionAlloc(allocator: std.mem.Allocator, endpoint: *const Endpoint) ![]u8 {
    const url = try endpoint.urlAlloc(allocator);
    defer allocator.free(url);
    const authorization = try endpoint.authorizationAlloc(allocator);
    defer allocator.free(authorization);
    const encoded_url = try std.json.Stringify.valueAlloc(allocator, url, .{});
    defer allocator.free(encoded_url);
    const encoded_authorization = try std.json.Stringify.valueAlloc(allocator, authorization, .{});
    defer allocator.free(encoded_authorization);

    var writer: std.Io.Writer.Allocating = .init(allocator);
    errdefer writer.deinit();
    try writer.writer.writeAll(PI_MARKER);
    try writer.writer.writeAll(
        \\import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
        \\import { Type } from "typebox";
        \\
        \\const MCP_PROTOCOL = "2026-07-28";
        \\const MCP_URL =
    );
    try writer.writer.writeAll(encoded_url);
    try writer.writer.writeAll(
        \\;
        \\const AUTHORIZATION =
    );
    try writer.writer.writeAll(encoded_authorization);
    try writer.writer.writeAll(
        \\;
        \\let nextId = 1;
        \\
        \\async function request(method: string, params: Record<string, unknown>, name?: string, signal?: AbortSignal): Promise<any> {
        \\  const routedParams = {
        \\    ...params,
        \\    _meta: {
        \\      "io.modelcontextprotocol/protocolVersion": MCP_PROTOCOL,
        \\      "io.modelcontextprotocol/clientInfo": { name: "pi", version: "verde-managed" },
        \\      "io.modelcontextprotocol/clientCapabilities": {},
        \\    },
        \\  };
        \\  const headers: Record<string, string> = {
        \\    "Authorization": AUTHORIZATION,
        \\    "Content-Type": "application/json",
        \\    "Accept": "application/json, text/event-stream",
        \\    "MCP-Protocol-Version": MCP_PROTOCOL,
        \\    "Mcp-Method": method,
        \\    "X-Verde-MCP-Client": "pi",
        \\    "X-Verde-MCP-Managed": "1",
        \\  };
        \\  if (name) headers["Mcp-Name"] = name;
        \\  const response = await fetch(MCP_URL, {
        \\    method: "POST",
        \\    headers,
        \\    body: JSON.stringify({ jsonrpc: "2.0", id: nextId++, method, params: routedParams }),
        \\    signal,
        \\  });
        \\  const payload = await response.json() as any;
        \\  if (!response.ok || payload.error) throw new Error(payload.error?.message ?? `Verde MCP HTTP ${response.status}`);
        \\  return payload.result;
        \\}
        \\
        \\function resultText(result: any): string {
        \\  if (Array.isArray(result?.content)) {
        \\    const text = result.content.filter((item: any) => item?.type === "text").map((item: any) => item.text).join("\\n");
        \\    if (text) return text;
        \\  }
        \\  return JSON.stringify(result);
        \\}
        \\
        \\export default async function (pi: ExtensionAPI) {
        \\  await request("server/discover", {});
        \\  const catalog = await request("tools/list", {});
        \\  for (const tool of catalog.tools ?? []) {
        \\    pi.registerTool({
        \\      name: `verde_${tool.name}`,
        \\      label: `Verde: ${tool.name}`,
        \\      description: tool.description ?? `Call Verde MCP tool ${tool.name}`,
        \\      parameters: Type.Unsafe(tool.inputSchema),
        \\      async execute(_toolCallId, params, signal) {
        \\        const result = await request("tools/call", { name: tool.name, arguments: params }, tool.name, signal);
        \\        if (result?.isError) throw new Error(resultText(result));
        \\        return { content: result?.content ?? [{ type: "text", text: resultText(result) }], details: result };
        \\      },
        \\    });
        \\  }
        \\}
        \\
    );
    return writer.toOwnedSlice();
}

fn inspectManagedFileAtHome(
    allocator: std.mem.Allocator,
    home: []const u8,
    relative_path: []const u8,
    marker: []const u8,
) RegistrationStatus {
    const path = configPathAlloc(allocator, home, relative_path) catch return .not_installed;
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const content = readFileIfPresent(allocator, threaded.io(), path) catch return .conflict;
    defer if (content) |bytes| allocator.free(bytes);
    const bytes = content orelse return .not_installed;
    return if (std.mem.startsWith(u8, bytes, marker)) .installed else .conflict;
}

fn removeManagedFileAtHome(
    allocator: std.mem.Allocator,
    home: []const u8,
    relative_path: []const u8,
    marker: []const u8,
) !void {
    const path = try configPathAlloc(allocator, home, relative_path);
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const content = try readFileIfPresent(allocator, io, path) orelse return;
    defer allocator.free(content);
    if (std.mem.startsWith(u8, content, marker)) try std.Io.Dir.cwd().deleteFile(io, path);
}

fn installFxAtHome(allocator: std.mem.Allocator, home: []const u8, endpoint: *const Endpoint) !void {
    try installJsonAtHome(allocator, home, endpoint, .fx, FX_SPEC);
    try removeManagedFileAtHome(allocator, home, ".fx/verde-mcp.enabled", LEGACY_FX_MARKER);
}

fn removeFxAtHome(allocator: std.mem.Allocator, home: []const u8) !void {
    try removeJsonAtHome(allocator, home, FX_SPEC);
    try removeManagedFileAtHome(allocator, home, ".fx/verde-mcp.enabled", LEGACY_FX_MARKER);
}

fn inspectJsonAtHome(allocator: std.mem.Allocator, home: []const u8, spec: JsonSpec) RegistrationStatus {
    const path = configPathAlloc(allocator, home, spec.relative_path) catch return .not_installed;
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const content = readFileIfPresent(allocator, threaded.io(), path) catch return .conflict;
    defer if (content) |bytes| allocator.free(bytes);
    const bytes = content orelse return .not_installed;
    var parsed = std.json.parseFromSlice(std.json.Value, allocator, bytes, .{}) catch return .conflict;
    defer parsed.deinit();
    if (parsed.value != .object) return .conflict;
    const section = parsed.value.object.get(spec.section_key) orelse return .not_installed;
    if (section != .object) return .conflict;
    const entry = section.object.get("verde") orelse return .not_installed;
    return if (jsonEntryManaged(entry, spec.environment_key)) .installed else .conflict;
}

fn installJsonAtHome(
    allocator: std.mem.Allocator,
    home: []const u8,
    endpoint: *const Endpoint,
    provider: Provider,
    spec: JsonSpec,
) !void {
    const path = try configPathAlloc(allocator, home, spec.relative_path);
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const existing = try readFileIfPresent(allocator, io, path);
    defer if (existing) |bytes| allocator.free(bytes);

    var parsed = if (existing) |bytes|
        try std.json.parseFromSlice(std.json.Value, allocator, bytes, .{})
    else
        try std.json.parseFromSlice(std.json.Value, allocator, "{}", .{});
    defer parsed.deinit();
    if (parsed.value != .object) return error.ProviderConfigNotObject;
    const arena = parsed.arena.allocator();
    const root = &parsed.value.object;
    if (root.getPtr(spec.section_key)) |section| {
        if (section.* != .object) return error.ProviderMcpSectionNotObject;
    } else {
        try root.put(arena, spec.section_key, .{ .object = .empty });
    }
    const section = &root.getPtr(spec.section_key).?.object;
    if (section.get("verde")) |entry| {
        if (!jsonEntryManaged(entry, spec.environment_key)) return error.ProviderMcpConflict;
    }
    try section.put(arena, "verde", try jsonManagedEntry(arena, endpoint, provider, spec));

    const encoded = try std.json.Stringify.valueAlloc(allocator, parsed.value, .{ .whitespace = .indent_2 });
    defer allocator.free(encoded);
    try writeFileAtomic(allocator, io, path, encoded);
}

fn removeJsonAtHome(allocator: std.mem.Allocator, home: []const u8, spec: JsonSpec) !void {
    const path = try configPathAlloc(allocator, home, spec.relative_path);
    defer allocator.free(path);
    var threaded: std.Io.Threaded = .init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const existing = try readFileIfPresent(allocator, io, path) orelse return;
    defer allocator.free(existing);
    var parsed = std.json.parseFromSlice(std.json.Value, allocator, existing, .{}) catch return;
    defer parsed.deinit();
    if (parsed.value != .object) return;
    const section_value = parsed.value.object.getPtr(spec.section_key) orelse return;
    if (section_value.* != .object) return;
    const entry = section_value.object.get("verde") orelse return;
    if (!jsonEntryManaged(entry, spec.environment_key)) return;
    _ = section_value.object.orderedRemove("verde");
    const encoded = try std.json.Stringify.valueAlloc(allocator, parsed.value, .{ .whitespace = .indent_2 });
    defer allocator.free(encoded);
    try writeFileAtomic(allocator, io, path, encoded);
}

fn jsonEntryManaged(entry: std.json.Value, environment_key: []const u8) bool {
    if (entry != .object) return false;
    if (entry.object.get(environment_key)) |environment| {
        if (environment == .object) {
            if (environment.object.get(MANAGED_ENV_KEY)) |marker| {
                if (marker == .string and std.mem.eql(u8, marker.string, MANAGED_ENV_VALUE)) return true;
            }
        }
    }
    const headers = entry.object.get("headers") orelse return false;
    if (headers != .object) return false;
    const marker = headers.object.get(MANAGED_HEADER_KEY) orelse return false;
    return marker == .string and std.mem.eql(u8, marker.string, MANAGED_ENV_VALUE);
}

fn jsonManagedEntry(
    arena: std.mem.Allocator,
    endpoint: *const Endpoint,
    provider: Provider,
    spec: JsonSpec,
) !std.json.Value {
    const url = try endpoint.urlAlloc(arena);
    var headers: std.json.ObjectMap = .empty;
    if (spec.bearer_token_env == null) {
        const authorization = try endpoint.authorizationAlloc(arena);
        try headers.put(arena, "Authorization", .{ .string = authorization });
    }
    try headers.put(arena, CLIENT_HEADER_KEY, .{ .string = @tagName(provider) });
    try headers.put(arena, MANAGED_HEADER_KEY, .{ .string = MANAGED_ENV_VALUE });
    var entry: std.json.ObjectMap = .empty;
    if (spec.remote_type) |remote_type| try entry.put(arena, "type", .{ .string = remote_type });
    try entry.put(arena, "url", .{ .string = url });
    try entry.put(arena, "headers", .{ .object = headers });
    if (spec.bearer_token_env) |env_name| {
        try entry.put(arena, "bearer_token_env", .{ .string = env_name });
    }
    if (spec.enabled_key) |key| try entry.put(arena, key, .{ .bool = true });
    if (spec.disable_oauth) try entry.put(arena, "oauth", .{ .bool = false });
    return .{ .object = entry };
}

const TEST_TOKEN = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

fn testEndpoint(port: u16) Endpoint {
    return .{ .port = port, .token = @constCast(TEST_TOKEN) };
}

test "managed JSON registration preserves user servers and uninstalls only Verde" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const home = try std.fmt.allocPrint(std.testing.allocator, ".zig-cache/tmp/{s}", .{tmp.sub_path});
    defer std.testing.allocator.free(home);
    const claude_path = try configPathAlloc(std.testing.allocator, home, CLAUDE_SPEC.relative_path);
    defer std.testing.allocator.free(claude_path);
    const fx_path = try configPathAlloc(std.testing.allocator, home, FX_SPEC.relative_path);
    defer std.testing.allocator.free(fx_path);
    var threaded: std.Io.Threaded = .init(std.testing.allocator, .{});
    defer threaded.deinit();
    try writeFileAtomic(std.testing.allocator, threaded.io(), claude_path,
        \\{"mcpServers":{"user-server":{"command":"user-command"}}}
    );
    try writeFileAtomic(std.testing.allocator, threaded.io(), fx_path,
        \\{"mcp":{"user-server":{"type":"local","command":["user-command"]}}}
    );
    const endpoint = testEndpoint(47_371);
    const detected = [ALL_PROVIDERS.len]bool{ false, true, true, true, true, false, true, false };
    const installed = try installAtHome(std.testing.allocator, home, &endpoint, detected);
    try std.testing.expectEqual(RegistrationStatus.installed, installed.claude);
    try std.testing.expectEqual(RegistrationStatus.installed, installed.cursor);
    try std.testing.expectEqual(RegistrationStatus.installed, installed.opencode);
    try std.testing.expectEqual(RegistrationStatus.installed, installed.amp);
    try std.testing.expectEqual(RegistrationStatus.installed, installed.fx);

    const fx_installed = (try readFileIfPresent(std.testing.allocator, threaded.io(), fx_path)).?;
    defer std.testing.allocator.free(fx_installed);
    try std.testing.expect(std.mem.indexOf(u8, fx_installed, "\"bearer_token_env\": \"VERDE_MCP_TOKEN\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, fx_installed, "Authorization") == null);
    try std.testing.expect(std.mem.indexOf(u8, fx_installed, TEST_TOKEN) == null);

    try removeProviderAtHome(std.testing.allocator, home, .claude);
    try std.testing.expectEqual(RegistrationStatus.not_installed, inspectProviderAtHome(std.testing.allocator, home, .claude));
    const remaining = (try readFileIfPresent(std.testing.allocator, threaded.io(), claude_path)).?;
    defer std.testing.allocator.free(remaining);
    try std.testing.expect(std.mem.indexOf(u8, remaining, "user-server") != null);
    try std.testing.expect(std.mem.indexOf(u8, remaining, "user-command") != null);

    try removeProviderAtHome(std.testing.allocator, home, .fx);
    try std.testing.expectEqual(RegistrationStatus.not_installed, inspectProviderAtHome(std.testing.allocator, home, .fx));
    const fx_remaining = (try readFileIfPresent(std.testing.allocator, threaded.io(), fx_path)).?;
    defer std.testing.allocator.free(fx_remaining);
    try std.testing.expect(std.mem.indexOf(u8, fx_remaining, "user-server") != null);
    try std.testing.expect(std.mem.indexOf(u8, fx_remaining, "user-command") != null);
}

test "Codex managed block is idempotent and preserves surrounding TOML" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const home = try std.fmt.allocPrint(std.testing.allocator, ".zig-cache/tmp/{s}", .{tmp.sub_path});
    defer std.testing.allocator.free(home);
    const path = try configPathAlloc(std.testing.allocator, home, ".codex/config.toml");
    defer std.testing.allocator.free(path);
    var threaded: std.Io.Threaded = .init(std.testing.allocator, .{});
    defer threaded.deinit();
    try ensureParentDir(threaded.io(), path);
    try writeFileAtomic(std.testing.allocator, threaded.io(), path, "model = \"gpt-5\"\n");

    const first_endpoint = testEndpoint(47_371);
    const second_endpoint = testEndpoint(47_372);
    try installCodexAtHome(std.testing.allocator, home, &first_endpoint);
    try installCodexAtHome(std.testing.allocator, home, &second_endpoint);
    const content = (try readFileIfPresent(std.testing.allocator, threaded.io(), path)).?;
    defer std.testing.allocator.free(content);
    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, content, CODEX_BLOCK_BEGIN));
    try std.testing.expect(std.mem.indexOf(u8, content, "model = \"gpt-5\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "http://127.0.0.1:47372/mcp") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "http_headers") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "default_tools_approval_mode = \"approve\"") != null);

    try removeCodexAtHome(std.testing.allocator, home);
    const removed = (try readFileIfPresent(std.testing.allocator, threaded.io(), path)).?;
    defer std.testing.allocator.free(removed);
    try std.testing.expectEqualStrings("model = \"gpt-5\"\n", removed);
}

test "unmanaged provider entry is reported as a conflict" {
    var parsed = try std.json.parseFromSlice(std.json.Value, std.testing.allocator,
        \\{"command":"other","env":{}}
    , .{});
    defer parsed.deinit();
    try std.testing.expect(!jsonEntryManaged(parsed.value, "env"));
}

test "an unmanaged verde entry does not block other providers" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const home = try std.fmt.allocPrint(std.testing.allocator, ".zig-cache/tmp/{s}", .{tmp.sub_path});
    defer std.testing.allocator.free(home);
    const claude_path = try configPathAlloc(std.testing.allocator, home, CLAUDE_SPEC.relative_path);
    defer std.testing.allocator.free(claude_path);
    var threaded: std.Io.Threaded = .init(std.testing.allocator, .{});
    defer threaded.deinit();
    try writeFileAtomic(std.testing.allocator, threaded.io(), claude_path,
        \\{"mcpServers":{"verde":{"command":"user-command"}}}
    );

    const endpoint = testEndpoint(47_371);
    const summary = try installAtHome(
        std.testing.allocator,
        home,
        &endpoint,
        .{ false, true, true, false, false, false, false, false },
    );
    try std.testing.expectEqual(RegistrationStatus.conflict, summary.claude);
    try std.testing.expectEqual(RegistrationStatus.installed, summary.cursor);
}

test "OpenCode registration preserves an existing schema config" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const home = try std.fmt.allocPrint(std.testing.allocator, ".zig-cache/tmp/{s}", .{tmp.sub_path});
    defer std.testing.allocator.free(home);
    const path = try configPathAlloc(std.testing.allocator, home, OPENCODE_SPEC.relative_path);
    defer std.testing.allocator.free(path);
    var threaded: std.Io.Threaded = .init(std.testing.allocator, .{});
    defer threaded.deinit();
    try writeFileAtomic(std.testing.allocator, threaded.io(), path,
        \\{
        \\  "$schema": "https://opencode.ai/config.json",
        \\  "autoupdate": false,
        \\  "disabled_providers": ["openrouter", "google"]
        \\}
    );

    const endpoint = testEndpoint(47_371);
    try installJsonAtHome(std.testing.allocator, home, &endpoint, .opencode, OPENCODE_SPEC);
    try std.testing.expectEqual(RegistrationStatus.installed, inspectJsonAtHome(std.testing.allocator, home, OPENCODE_SPEC));
    const updated = (try readFileIfPresent(std.testing.allocator, threaded.io(), path)).?;
    defer std.testing.allocator.free(updated);
    try std.testing.expect(std.mem.indexOf(u8, updated, "disabled_providers") != null);
    try std.testing.expect(std.mem.indexOf(u8, updated, MANAGED_HEADER_KEY) != null);
    try std.testing.expect(std.mem.indexOf(u8, updated, "\"type\": \"remote\"") != null);
}

test "OpenCode registration supports a symlinked config directory" {
    if (builtin.os.tag == .windows) return error.SkipZigTest;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const home = try std.fmt.allocPrint(std.testing.allocator, ".zig-cache/tmp/{s}", .{tmp.sub_path});
    defer std.testing.allocator.free(home);
    const config_dir = try configPathAlloc(std.testing.allocator, home, ".config");
    defer std.testing.allocator.free(config_dir);
    const target_dir = try configPathAlloc(std.testing.allocator, home, "opencode-target");
    defer std.testing.allocator.free(target_dir);
    const link_path = try configPathAlloc(std.testing.allocator, config_dir, "opencode");
    defer std.testing.allocator.free(link_path);
    var threaded: std.Io.Threaded = .init(std.testing.allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    try std.Io.Dir.cwd().createDirPath(io, config_dir);
    try std.Io.Dir.cwd().createDirPath(io, target_dir);
    try std.Io.Dir.cwd().symLink(io, "../opencode-target", link_path, .{ .is_directory = true });

    const path = try configPathAlloc(std.testing.allocator, home, OPENCODE_SPEC.relative_path);
    defer std.testing.allocator.free(path);
    try writeFileAtomic(std.testing.allocator, io, path, "{}");
    const endpoint = testEndpoint(47_371);
    try installJsonAtHome(std.testing.allocator, home, &endpoint, .opencode, OPENCODE_SPEC);
    try std.testing.expectEqual(RegistrationStatus.installed, inspectJsonAtHome(std.testing.allocator, home, OPENCODE_SPEC));
}

test "existing provider config is detected without relying on PATH" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const home = try std.fmt.allocPrint(std.testing.allocator, ".zig-cache/tmp/{s}", .{tmp.sub_path});
    defer std.testing.allocator.free(home);
    const path = try configPathAlloc(std.testing.allocator, home, OPENCODE_SPEC.relative_path);
    defer std.testing.allocator.free(path);
    var threaded: std.Io.Threaded = .init(std.testing.allocator, .{});
    defer threaded.deinit();
    try writeFileAtomic(std.testing.allocator, threaded.io(), path, "{}");

    try std.testing.expect(providerConfigExistsAtHome(std.testing.allocator, home, .opencode));
    try std.testing.expect(!providerConfigExistsAtHome(std.testing.allocator, home, .amp));
}

test "all eight provider registrations use the daemon HTTP endpoint" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const home = try std.fmt.allocPrint(std.testing.allocator, ".zig-cache/tmp/{s}", .{tmp.sub_path});
    defer std.testing.allocator.free(home);
    const endpoint = testEndpoint(47_379);
    const summary = try installAtHome(
        std.testing.allocator,
        home,
        &endpoint,
        [_]bool{true} ** ALL_PROVIDERS.len,
    );
    try std.testing.expectEqual(@as(usize, 8), ALL_PROVIDERS.len);
    try std.testing.expectEqual(@as(usize, 8), summary.detectedCount());
    try std.testing.expectEqual(@as(usize, 8), summary.installedCount());
    try std.testing.expect(summary.allDetectedInstalled());

    var threaded: std.Io.Threaded = .init(std.testing.allocator, .{});
    defer threaded.deinit();
    inline for (.{
        ".codex/config.toml",
        ".claude.json",
        ".cursor/mcp.json",
        ".config/opencode/opencode.json",
        ".config/amp/settings.json",
        ".pi/agent/extensions/verde-mcp.ts",
        ".grok/config.toml",
    }) |relative_path| {
        const path = try configPathAlloc(std.testing.allocator, home, relative_path);
        defer std.testing.allocator.free(path);
        const content = (try readFileIfPresent(std.testing.allocator, threaded.io(), path)).?;
        defer std.testing.allocator.free(content);
        try std.testing.expect(std.mem.indexOf(u8, content, "http://127.0.0.1:47379/mcp") != null);
    }
    const pi_path = try configPathAlloc(std.testing.allocator, home, ".pi/agent/extensions/verde-mcp.ts");
    defer std.testing.allocator.free(pi_path);
    const pi_source = (try readFileIfPresent(std.testing.allocator, threaded.io(), pi_path)).?;
    defer std.testing.allocator.free(pi_source);
    try std.testing.expect(std.mem.indexOf(u8, pi_source, "2026-07-28") != null);
    try std.testing.expect(std.mem.indexOf(u8, pi_source, "clientCapabilities") != null);
}
