//! CPU-side render commands shared by components and the SDL_GPU renderer.

const Self = @This();
const std = @import("std");

pub const GpuRenderPass = anyopaque;

pub const Color = extern struct {
    r: f32 = 1.0,
    g: f32 = 1.0,
    b: f32 = 1.0,
    a: f32 = 1.0,

    pub const white: Color = .{};
    pub const transparent: Color = .{ .a = 0.0 };
    pub const black: Color = .{ .r = 0.0, .g = 0.0, .b = 0.0 };
};

pub const Vec2 = extern struct {
    x: f32 = 0.0,
    y: f32 = 0.0,
};

pub const Rect = extern struct {
    x: f32 = 0.0,
    y: f32 = 0.0,
    w: f32 = 0.0,
    h: f32 = 0.0,

    pub fn contains(self: Rect, point: Vec2) bool {
        return point.x >= self.x and point.x < self.x + self.w and
            point.y >= self.y and point.y < self.y + self.h;
    }
};

pub const TextureId = extern struct {
    value: u32 = 0,

    pub const invalid: TextureId = .{};

    pub fn init(value: u32) TextureId {
        return .{ .value = value };
    }

    pub fn valid(self: TextureId) bool {
        return self.value != 0;
    }
};

pub const Vertex = extern struct {
    pos: Vec2,
    uv: Vec2,
    color: Color,
};

pub const CommandKind = enum {
    rect,
    triangle,
    text,
    image,
    cursor,
    selection,
    scrollbar,
};

pub const FontRole = enum {
    ui,
    ui_bold,
    icon,
    mono,
};

pub const TextRun = struct {
    /// Slice into the command text. Frame-lifetime with the owning command text.
    text: []const u8 = "",
    byte_start: usize = 0,
    byte_end: usize = 0,
    x: f32 = 0.0,
    y: f32 = 0.0,
    font_size: f32 = 16.0,
    line_height: f32 = 20.0,
    color: Color = Color.white,
    clip: ?Rect = null,
    /// Renderer-neutral font role. Host renderers map this to their own font atlas.
    font_role: ?FontRole = null,
    /// Optional host-defined font id for apps that prefer numeric atlas handles.
    font_id: ?u32 = null,
};

pub const Command = struct {
    kind: CommandKind,
    rect: Rect,
    p0: Vec2 = .{},
    p1: Vec2 = .{},
    p2: Vec2 = .{},
    uv: Rect = .{},
    color: Color,
    texture: TextureId = .invalid,
    /// Frame-lifetime text slice. Callers must keep it alive until the batch is consumed.
    text: []const u8 = "",
    /// Laid-out text runs generated by Palette. When non-empty, host renderers
    /// should draw these runs directly instead of re-wrapping `text`.
    text_runs: []const TextRun = &.{},
    text_run_start: usize = 0,
    text_run_count: usize = 0,
    font_size: f32 = 16.0,
    font_role: ?FontRole = null,
    font_id: ?u32 = null,
    clip: ?Rect = null,
    scroll: Vec2 = .{},
    glyph_width: f32 = 8.8,
    line_height: f32 = 20.0,
    wrap: bool = false,
    radius: f32 = 0.0,
    border_width: f32 = 0.0,
    border_color: ?Color = null,
    /// Higher z-index commands draw later. Equal z-index preserves insertion order.
    z_index: i32 = 0,
};

pub const RenderBatch = struct {
    commands: std.ArrayList(Command) = .empty,
    text_runs: std.ArrayList(TextRun) = .empty,
    current_z_index: i32 = 0,

    pub fn deinit(self: *RenderBatch, allocator: std.mem.Allocator) void {
        self.commands.deinit(allocator);
        self.text_runs.deinit(allocator);
    }

    pub fn clear(self: *RenderBatch) void {
        self.commands.clearRetainingCapacity();
        self.text_runs.clearRetainingCapacity();
        self.current_z_index = 0;
    }

    pub fn setZIndex(self: *RenderBatch, z_index: i32) i32 {
        const previous = self.current_z_index;
        self.current_z_index = z_index;
        return previous;
    }

    pub fn restoreZIndex(self: *RenderBatch, z_index: i32) void {
        self.current_z_index = z_index;
    }

    pub fn rect(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, color: Color) !void {
        try self.appendCommand(allocator, .{ .kind = .rect, .rect = r, .color = color });
    }

    pub fn triangle(self: *RenderBatch, allocator: std.mem.Allocator, p0: Vec2, p1: Vec2, p2: Vec2, color: Color) !void {
        try self.appendCommand(allocator, .{
            .kind = .triangle,
            .rect = .{},
            .p0 = p0,
            .p1 = p1,
            .p2 = p2,
            .color = color,
        });
    }

    pub fn roundedRect(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, color: Color, radius: f32) !void {
        try self.appendCommand(allocator, .{ .kind = .rect, .rect = r, .color = color, .radius = radius });
    }

    pub fn rectBorder(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, color: Color, radius: f32, width: f32) !void {
        try self.appendCommand(allocator, .{
            .kind = .rect,
            .rect = r,
            .color = Color.transparent,
            .radius = radius,
            .border_width = width,
            .border_color = color,
        });
    }

    pub fn panel(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, background: Color, border: ?Color, radius: f32, border_width: f32) !void {
        try self.appendCommand(allocator, .{
            .kind = .rect,
            .rect = r,
            .color = background,
            .radius = radius,
            .border_width = border_width,
            .border_color = border,
        });
    }

    pub fn glyph(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, uv: Rect, color: Color) !void {
        try self.image(allocator, r, .invalid, uv, color, null);
    }

    pub fn image(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, texture: TextureId, uv: Rect, tint: Color, clip: ?Rect) !void {
        try self.appendCommand(allocator, .{
            .kind = .image,
            .rect = r,
            .uv = uv,
            .color = tint,
            .texture = texture,
            .clip = clip,
        });
    }

    /// Appends a text command. The `value` slice is frame-lifetime and must remain
    /// valid until the batch is consumed by a renderer.
    pub fn text(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, value: []const u8, color: Color, font_size: f32, clip: ?Rect) !void {
        try self.appendCommand(allocator, .{
            .kind = .text,
            .rect = r,
            .color = color,
            .text = value,
            .font_size = font_size,
            .clip = clip,
            .glyph_width = font_size * 0.55,
            .line_height = font_size * 1.25,
        });
    }

    pub fn roleText(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, value: []const u8, color: Color, font_size: f32, font_role: ?FontRole, font_id: ?u32, clip: ?Rect) !void {
        try self.appendCommand(allocator, .{
            .kind = .text,
            .rect = r,
            .color = color,
            .text = value,
            .font_size = font_size,
            .font_role = font_role,
            .font_id = font_id,
            .clip = clip,
            .glyph_width = font_size * 0.55,
            .line_height = font_size * 1.25,
        });
    }

    /// Appends a laid-out text command. The `value` slice is frame-lifetime; the
    /// run descriptors are copied into the batch and remain valid until `clear`
    /// or `deinit`.
    pub fn textRuns(
        self: *RenderBatch,
        allocator: std.mem.Allocator,
        r: Rect,
        value: []const u8,
        runs: []const TextRun,
        color: Color,
        font_size: f32,
        clip: ?Rect,
        line_height: f32,
        glyph_width: f32,
    ) !void {
        const start = self.text_runs.items.len;
        try self.text_runs.appendSlice(allocator, runs);
        const stored = self.text_runs.items[start .. start + runs.len];
        try self.appendCommand(allocator, .{
            .kind = .text,
            .rect = r,
            .color = color,
            .text = value,
            .text_runs = stored,
            .text_run_start = start,
            .text_run_count = runs.len,
            .font_size = font_size,
            .clip = clip,
            .line_height = line_height,
            .glyph_width = glyph_width,
        });
        self.refreshTextRunSlices();
    }

    /// Appends fixed-cell wrapped text. TextArea uses this so rendering, hit
    /// testing, cursor placement, selection, and scrolling share one layout model.
    pub fn fixedText(
        self: *RenderBatch,
        allocator: std.mem.Allocator,
        r: Rect,
        value: []const u8,
        color: Color,
        font_size: f32,
        clip: ?Rect,
        scroll_value: Vec2,
        glyph_width: f32,
        line_height: f32,
        wrap: bool,
    ) !void {
        try self.appendCommand(allocator, .{
            .kind = .text,
            .rect = r,
            .color = color,
            .text = value,
            .font_size = font_size,
            .clip = clip,
            .scroll = scroll_value,
            .glyph_width = glyph_width,
            .line_height = line_height,
            .wrap = wrap,
        });
    }

    pub fn cursor(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, color: Color) !void {
        try self.appendCommand(allocator, .{ .kind = .cursor, .rect = r, .color = color });
    }

    pub fn selection(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, color: Color) !void {
        try self.appendCommand(allocator, .{ .kind = .selection, .rect = r, .color = color });
    }

    pub fn scrollbar(self: *RenderBatch, allocator: std.mem.Allocator, r: Rect, color: Color) !void {
        try self.appendCommand(allocator, .{ .kind = .scrollbar, .rect = r, .color = color });
    }

    fn appendCommand(self: *RenderBatch, allocator: std.mem.Allocator, command: Command) !void {
        var next = command;
        next.z_index = self.current_z_index;
        try self.commands.append(allocator, next);
        var index = self.commands.items.len - 1;
        while (index > 0 and self.commands.items[index - 1].z_index > next.z_index) : (index -= 1) {
            self.commands.items[index] = self.commands.items[index - 1];
        }
        self.commands.items[index] = next;
    }

    fn refreshTextRunSlices(self: *RenderBatch) void {
        for (self.commands.items) |*command| {
            if (command.text_run_count == 0) continue;
            command.text_runs = self.text_runs.items[command.text_run_start .. command.text_run_start + command.text_run_count];
        }
    }
};

test "rect contains points inside bounds" {
    const rect_value: Rect = .{ .x = 10, .y = 20, .w = 30, .h = 40 };
    try std.testing.expect(rect_value.contains(.{ .x = 10, .y = 20 }));
    try std.testing.expect(!rect_value.contains(.{ .x = 40, .y = 20 }));
}

test "image command carries texture and uv" {
    var batch: RenderBatch = .{};
    defer batch.deinit(std.testing.allocator);

    try batch.image(std.testing.allocator, .{ .w = 24, .h = 16 }, TextureId.init(7), .{ .x = 0.25, .y = 0.5, .w = 0.5, .h = 0.25 }, Color.white, .{ .w = 10, .h = 10 });

    try std.testing.expectEqual(CommandKind.image, batch.commands.items[0].kind);
    try std.testing.expectEqual(@as(u32, 7), batch.commands.items[0].texture.value);
    try std.testing.expectEqual(@as(f32, 0.25), batch.commands.items[0].uv.x);
    try std.testing.expect(batch.commands.items[0].clip != null);
}

test "commands are stably sorted by z-index" {
    var batch: RenderBatch = .{};
    defer batch.deinit(std.testing.allocator);

    _ = batch.setZIndex(10);
    try batch.rect(std.testing.allocator, .{ .x = 10 }, Color.white);
    _ = batch.setZIndex(0);
    try batch.rect(std.testing.allocator, .{ .x = 0 }, Color.white);
    try batch.rect(std.testing.allocator, .{ .x = 1 }, Color.white);
    _ = batch.setZIndex(5);
    try batch.rect(std.testing.allocator, .{ .x = 5 }, Color.white);

    try std.testing.expectEqual(@as(f32, 0), batch.commands.items[0].rect.x);
    try std.testing.expectEqual(@as(f32, 1), batch.commands.items[1].rect.x);
    try std.testing.expectEqual(@as(f32, 5), batch.commands.items[2].rect.x);
    try std.testing.expectEqual(@as(f32, 10), batch.commands.items[3].rect.x);
}

test "panel command carries renderer-neutral shape style" {
    var batch: RenderBatch = .{};
    defer batch.deinit(std.testing.allocator);

    try batch.panel(std.testing.allocator, .{ .w = 20, .h = 10 }, Color.black, Color.white, 6, 2);

    try std.testing.expectEqual(CommandKind.rect, batch.commands.items[0].kind);
    try std.testing.expectEqual(@as(f32, 6), batch.commands.items[0].radius);
    try std.testing.expectEqual(@as(f32, 2), batch.commands.items[0].border_width);
    try std.testing.expect(batch.commands.items[0].border_color != null);
}
