//! Deterministic comptime reflection of the exported local wire types.
const std = @import("std");
const registry = @import("model_registry.zig").types;
const Language = enum { kotlin, swift };
const header = "// Generated by `mise run mobile-models-generate`. DO NOT EDIT.\n";

pub fn generate(comptime language: Language) []const u8 {
    @setEvalBranchQuota(2_000_000);
    comptime var out: []const u8 = header ++ switch (language) {
        .kotlin => "package dev.verdeai.core\n\nimport kotlinx.serialization.Serializable\nimport kotlinx.serialization.SerialName\nimport kotlinx.serialization.json.Json\nimport kotlinx.serialization.json.JsonElement\n\n// Encode Event/Effect through their sealed base type to include the discriminator.\nval CoreJson = Json { ignoreUnknownKeys = true; encodeDefaults = true; explicitNulls = true }\n\n",
        .swift => "import Foundation\n\nprivate enum ModelDiscriminator: String, CodingKey { case type }\n\n" ++ @embedFile("codegen/JSONValue.swift") ++ "\n",
    };
    inline for (registry, 0..) |entry, i| {
        inline for (registry, 0..) |previous, j| {
            if (j < i and (std.mem.eql(u8, entry[0], previous[0]) or entry[1] == previous[1])) @compileError("duplicate model registry entry");
        }
        out = out ++ declaration(entry[1], entry[0], language, null, null);
    }
    return std.mem.trimEnd(u8, out, "\n") ++ "\n";
}

fn registered(comptime T: type) ?[]const u8 {
    inline for (registry) |entry| if (T == entry[1]) return entry[0];
    return null;
}

fn pascal(comptime name: []const u8) []const u8 {
    comptime var out: []const u8 = "";
    comptime var upper = true;
    inline for (name) |c| {
        if (c == '_') {
            upper = true;
        } else {
            out = out ++ [_]u8{if (upper) std.ascii.toUpper(c) else c};
            upper = false;
        }
    }
    return out;
}

fn typeName(comptime T: type, comptime suggested: []const u8, comptime lang: Language) []const u8 {
    if (T == std.json.Value) return if (lang == .kotlin) "JsonElement" else "JSONValue";
    if (registered(T)) |name| return name;
    return switch (@typeInfo(T)) {
        .bool => if (lang == .kotlin) "Boolean" else "Bool",
        .int => |info| if (lang == .kotlin)
            (if (info.signedness == .unsigned and info.bits == 64) "ULong" else if (info.bits > 16) "Long" else "Int")
        else
            std.fmt.comptimePrint("{s}Int{d}", .{ if (info.signedness == .unsigned) "U" else "", info.bits }),
        .float => |info| if (info.bits == 32) "Float" else if (info.bits == 64) "Double" else @compileError("unsupported float width"),
        .optional => |info| typeName(info.child, suggested, lang) ++ "?",
        .pointer => |info| if (info.size != .slice) @compileError("model pointers must be slices") else if (info.child == u8) "String" else if (lang == .kotlin) "List<" ++ typeName(info.child, suggested, lang) ++ ">" else "[" ++ typeName(info.child, suggested, lang) ++ "]",
        .@"struct", .@"enum", .@"union" => suggested,
        else => @compileError("unsupported model type: " ++ @typeName(T)),
    };
}

fn nested(comptime T: type, comptime name: []const u8, comptime lang: Language) []const u8 {
    if (T == std.json.Value or registered(T) != null) return "";
    return switch (@typeInfo(T)) {
        .optional => |info| nested(info.child, name, lang),
        .pointer => |info| if (info.size == .slice) nested(info.child, name, lang) else @compileError("model pointers must be slices"),
        .@"struct", .@"enum", .@"union" => declaration(T, name, lang, null, null),
        else => "",
    };
}

fn defaultLiteral(comptime value: anytype, comptime suggested: []const u8, comptime lang: Language) []const u8 {
    const T = @TypeOf(value);
    if (@typeInfo(T) == .optional) {
        if (value) |v| return defaultLiteral(v, suggested, lang);
    }
    if (@typeInfo(T) == .pointer) {
        const info = @typeInfo(T).pointer;
        if (info.size == .slice and info.child != u8 and value.len == 0) return if (lang == .kotlin) "emptyList()" else "[]";
    }
    if (@typeInfo(T) == .@"enum") {
        return (if (lang == .kotlin) typeName(T, suggested, lang) else "") ++ ".`" ++ @tagName(value) ++ "`";
    }
    return literal(value, lang);
}

fn literal(comptime value: anytype, comptime lang: Language) []const u8 {
    return switch (@typeInfo(@TypeOf(value))) {
        .optional => if (value) |v| literal(v, lang) else if (lang == .kotlin) "null" else "nil",
        .bool => if (value) "true" else "false",
        .int => |info| std.fmt.comptimePrint("{d}{s}", .{ value, if (lang == .kotlin and info.signedness == .unsigned and info.bits == 64) "uL" else "" }),
        .pointer => |info| if (info.size == .slice and info.child == u8) quote(value, lang) else @compileError("unsupported model default"),
        .@"enum" => ".`" ++ @tagName(value) ++ "`",
        else => @compileError("unsupported model default"),
    };
}

fn quote(comptime value: []const u8, comptime lang: Language) []const u8 {
    comptime var out: []const u8 = "\"";
    inline for (value) |c| {
        out = out ++ switch (c) {
            '"' => "\\\"",
            '\\' => "\\\\",
            '\n' => "\\n",
            '\r' => "\\r",
            '\t' => "\\t",
            // Kotlin interpolation must never interpret a Zig default.
            '$' => if (lang == .kotlin) "${'$'}" else "$",
            else => if (c < 32) @compileError("unsupported control character in default") else &[_]u8{c},
        };
    }
    return out ++ "\"";
}

fn declaration(comptime T: type, comptime name: []const u8, comptime lang: Language, comptime parent: ?[]const u8, comptime tag: ?[]const u8) []const u8 {
    comptime var out: []const u8 = "";
    switch (@typeInfo(T)) {
        .@"struct" => |info| {
            inline for (info.fields) |field| out = out ++ nested(field.type, name ++ pascal(field.name), lang);
            if (lang == .kotlin) {
                out = out ++ "@Serializable\n";
                if (tag) |t| out = out ++ "@SerialName(\"" ++ t ++ "\")\n";
                out = out ++ "data class " ++ name ++ "(\n";
                inline for (info.fields) |field| {
                    out = out ++ "    val `" ++ field.name ++ "`: " ++ typeName(field.type, name ++ pascal(field.name), lang);
                    if (field.defaultValue()) |value| out = out ++ " = " ++ defaultLiteral(value, name ++ pascal(field.name), lang);
                    out = out ++ ",\n";
                }
                out = out ++ ")" ++ (if (parent) |p| " : " ++ p ++ "()" else "") ++ "\n\n";
            } else {
                out = out ++ "struct " ++ name ++ ": Codable {\n";
                inline for (info.fields) |field| {
                    out = out ++ "    var `" ++ field.name ++ "`: " ++ typeName(field.type, name ++ pascal(field.name), lang);
                    if (field.defaultValue()) |value| out = out ++ " = " ++ defaultLiteral(value, name ++ pascal(field.name), lang);
                    out = out ++ "\n";
                }
                out = out ++ "}\n\nextension " ++ name ++ " {\n    private enum CodingKeys: String, CodingKey {\n";
                inline for (info.fields) |field| out = out ++ "        case `" ++ field.name ++ "`\n";
                out = out ++ "    }\n    init(from decoder: Decoder) throws {\n        let c = try decoder.container(keyedBy: CodingKeys.self)\n";
                inline for (info.fields) |field| {
                    const optional = @typeInfo(field.type) == .optional;
                    const base = if (optional) @typeInfo(field.type).optional.child else field.type;
                    const default = field.defaultValue();
                    if (default) |value| out = out ++ "        if !c.contains(.`" ++ field.name ++ "`) { self.`" ++ field.name ++ "` = " ++ defaultLiteral(value, name ++ pascal(field.name), lang) ++ " } else {\n";
                    out = out ++ "        self.`" ++ field.name ++ "` = try c." ++ (if (optional) "decodeIfPresent" else "decode") ++ "(" ++ typeName(base, name ++ pascal(field.name), lang) ++ ".self, forKey: .`" ++ field.name ++ "`)";
                    out = out ++ "\n";
                    if (default != null) out = out ++ "        }\n";
                }
                out = out ++ "    }\n    func encode(to encoder: Encoder) throws {\n        var c = encoder.container(keyedBy: CodingKeys.self)\n";
                // encode (not encodeIfPresent) preserves required explicit nulls.
                inline for (info.fields) |field| out = out ++ "        try c.encode(self.`" ++ field.name ++ "`, forKey: .`" ++ field.name ++ "`)\n";
                if (tag) |t| out = out ++ "        var tag = encoder.container(keyedBy: ModelDiscriminator.self)\n        try tag.encode(\"" ++ t ++ "\", forKey: .type)\n";
                out = out ++ "    }\n}\n\n";
            }
        },
        .@"enum" => |info| {
            out = out ++ (if (lang == .kotlin) "@Serializable\nenum class " else "enum ") ++ name ++ (if (lang == .kotlin) " {\n" else ": String, Codable {\n");
            inline for (info.fields) |field| out = out ++ (if (lang == .kotlin) "    `" else "    case `") ++ field.name ++ (if (lang == .kotlin) "`,\n" else "`\n");
            out = out ++ "}\n\n";
        },
        .@"union" => |info| {
            if (info.tag_type == null) @compileError("model unions need a tag");
            if (lang == .kotlin) {
                out = out ++ "@Serializable\nsealed class " ++ name ++ "\n\n";
            } else {
                out = out ++ "enum " ++ name ++ ": Codable {\n";
                inline for (info.fields) |field| out = out ++ "    case `" ++ field.name ++ "`(" ++ name ++ pascal(field.name) ++ ")\n";
                out = out ++ "    init(from decoder: Decoder) throws {\n        let c = try decoder.container(keyedBy: ModelDiscriminator.self)\n        let tag = try c.decode(String.self, forKey: .type)\n        switch tag {\n";
                inline for (info.fields) |field| out = out ++ "        case \"" ++ field.name ++ "\": self = .`" ++ field.name ++ "`(try " ++ name ++ pascal(field.name) ++ "(from: decoder))\n";
                out = out ++ "        default: throw DecodingError.dataCorruptedError(forKey: .type, in: c, debugDescription: \"Unknown model tag\")\n        }\n    }\n    func encode(to encoder: Encoder) throws {\n        switch self {\n";
                inline for (info.fields) |field| out = out ++ "        case .`" ++ field.name ++ "`(let value): try value.encode(to: encoder)\n";
                out = out ++ "        }\n    }\n}\n\n";
            }
            inline for (info.fields) |field| out = out ++ declaration(field.type, name ++ pascal(field.name), lang, name, field.name);
        },
        else => @compileError("registry roots must be structs, enums or tagged unions"),
    }
    return out;
}
